### ISSUE TITLE
Error: Request entity too large

### ISSUE THREAD

**Issue by arol** [rollbar/rollbar-ios#10]
When running the dSYM upload shell script the server responses with this error:

```
{
    "err": 1,
    "message": "Error: Request Entity Too Large"
}
```

In addition, is it possible to stop the build process (with an `exit(1)`), in case the api returns an error?

Thank you!

**Comment by coryvirok** [comment]
Hi @arol,

Sorry for the slow response. How large is the dSYM that you are trying to upload? We have the max upload size capped to 64MB.

**Comment by rokob** [comment]
Closing as this is old, reopen if this is still an issue.
