### ISSUE TITLE
build issue with alpha10

### ISSUE THREAD

**Issue by donhill** [rollbar/rollbar-ios#100]
I was working with your online support because I was seeing a "Unknown error" in my dashboard. They had me upgrade to alpha 10. After upgrade my build fails. 
<img width="525" alt="screen shot 2018-05-22 at 12 06 43 pm" src="https://user-images.githubusercontent.com/201891/40378260-a6489148-5db8-11e8-99f5-2c924d9d4297.png">

`ld: warning: directory not found for option '-F/Users/dhill/projects/ios/tow-provider-ios/Rollbar'
ld: could not reparse object file in bitcode bundle: 'Invalid bitcode version (Producer: '902.0.39.1_0' Reader: '900.0.39.2_0')', using libLTO version 'LLVM version 9.0.0, (clang-900.0.39.2)' for architecture arm64 clang: error: linker command failed with exit code 1 (use -v to see invocation)`

I reverted back to a zip I had from Feb/2018 and the build is fine.

I really need to get the latest as I am facing an issue that is incorrectly report in rollbar from some ios devices.

Thanks

**Comment by rokob** [comment]
The latest release https://github.com/rollbar/rollbar-ios/releases/tag/v1.0.0-alpha11 has a build for Xcode 9.2 which corresponds to `Reader: '900.0.39.2_0'`. Apple made some weird bitcode changes that broke builds.
