### ISSUE TITLE
"Rollbar/Rollbar.h" file not found when using CocoaPods

### ISSUE THREAD

**Issue by VicZhang1** [rollbar/rollbar-ios#103]
Hi,

I am using Rollbar.framework 1.0.0-alpha11, my current way is embed the Rollbar.framework into my repository and reference it in project.

Now I expect to use CocoaPods to manage it, so I added `pod 'Rollbar', '~> 1.0.0-alpha11'` and run `pod install` (as I have referenced **CorePlot** framework via CocoaPods successfully). Then I can not compile my project as it says **_"Rollbar/Rollbar.h" file not found_** .

Can someone help me?

Thanks

**Comment by rokob** [comment]
If you switched from using the framework to using CocoaPods you might have to clean out your build folder and make sure that the framework references were cleaned up. I just created a new project, added `pod 'Rollbar', '~> 1.0.0-alpha11'` to a new podfile, ran `pod install`, opened the workspace, and I was able to add the Header and everything built. So from a green-field project everything works, so I suspect it has to do with Xcode caching. Hitting option+shift+cmd+K in Xcode will clean out the build folder.
