### ISSUE TITLE
Build error: Shell Script Invocation Error with symbolication script

### ISSUE THREAD

**Issue by emrsn-SebastianVancea** [rollbar/rollbar-ios#11]
When trying to run the symbolication script:

Print: Entry, ":CFBundleVersion", Does Not Exist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
Traceback (most recent call last):
  File `/Users/sirIO/Library/Developer/Xcode/DerivedData/Geolink-gmcefbekcjjyivcorktofuzjxwhp/Build/Intermediates/Geolink.build/Debug-iphoneos/Geolink.build/Script-B34CF00E1A9F403E00F212D8.s`, line 27, in `<module>
    version, identifier = stdout.split()`
ValueError: too many values to unpack
Command /bin/sh failed with exit code 1

Thank you

**Comment by croemmich** [comment]
Same issue here.

**Comment by mohjay** [comment]
Having the same problem as well

**Comment by brianr** [comment]
Hey everyone - thanks for the report here. What version of xcode are you all using?

**Comment by bkobilansky** [comment]
Issue present in Xcode 6.3 (6D570)

**Comment by bkobilansky** [comment]
Looks like the files are never getting to the INSTALL_DIR to me. In my testing, I was not able to get Xcode to place any files in that location. 

Per the [build ref](https://developer.apple.com/library/ios/documentation/DeveloperTools/Reference/XcodeBuildSettingRef/1-Build_Setting_Reference/build_setting_ref.html#//apple_ref/doc/uid/TP40003931-CH3-SW23), it's just a folder in /tmp. That doesn't seem too crazy, so perhaps this is a new behavior or bug in Xcode 6.3?

I was able to use the BUILT_PRODUCTS_DIR as a workaround, but I'm not certain this will be valid for other projects - it's in DerivedData, so tread carefully.

Workaround:
`info_file_path = os.path.join(os.environ['BUILT_PRODUCTS_DIR'], os.environ['INFOPLIST_PATH'])`

**Comment by mohjay** [comment]
I'm using Xcode 6.3 (6D570) as well

**Comment by sodev** [comment]
Has this received any attention from anyone at RollBar yet?

**Comment by coryvirok** [comment]
Hey all. Sorry for the slow response. We are planning on getting this working very soon. Until then, you can try reverting this change to the upload script - https://github.com/rollbar/rollbar-ios/commit/3fb27c815eb79c6cbcee38eb90cecaf238b66930 or use @bkobilansky's workaround.

**Comment by AknEp** [comment]
I'm confused this problem with `Version 6.3.1 (6D1002)`

**Comment by sybohy** [comment]
Simple way to fix this in the meantime:

The info_file_path is not found, which cascades down to the CFBundleVersion and CFBundleIdentifier. For now I think you can fix the info_file_path path as such: 
`info_file_path = os.path.join(os.environ['SOURCE_ROOT'], os.environ['INFOPLIST_FILE'])`

this works in dev; not sure about release yet.

**Comment by Cyclic** [comment]
+1 @sybohy

**Comment by kshep** [comment]
I've been trying to figure out whether there's a canonical, definitive location for the plist file we should read version and identifier from so we can update the build script snippet. It seems like the location can change from project to project, and from one version of Xcode to the next, and there are examples scripts floating around that read it from any of the following locations:

```
- $TARGET_BUILD_DIR/$INFOPLIST_PATH
- $BUILT_PRODUCTS_DIR/$INFOPLIST_PATH
- $INSTALL_DIR/$INFOPLIST_PATH
- $CONFIGURATION_BUILD_DIR/$INFOPLIST_PATH
- $INFOPLIST_FILE
- $PRODUCT_SETTINGS_PATH
```

It's tempting to just add a note in our documentation that you see an error like:

```
Print: Entry, ":CFBundleVersion", Does Not Exist
Print: Entry, ":CFBundleIdentifier", Does Not Exist
```

It's because the command:

```
/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" -c "Print :CFBundleIdentifier” [file_location]
```

can't find the version and identifier in the file at ```[file_location]``` and that you'll need to update the ```info_file_path``` setting based on your project configuration and Xcode version.

Does that seem reasonable?

**Comment by coryvirok** [comment]
Will it always be in a project folder somewhere? If so, you could just
write some Python code to find it.

**Comment by kshep** [comment]
@coryvirok I'm not sure if it's always in the project folder, [in /tmp](https://github.com/rollbar/rollbar-ios/issues/11#issuecomment-93110421), or that there's only going to be a single plist file per project. And in some cases, the values PlistBuddy retrieves [contain placeholders](https://github.com/rollbar/rollbar-ios/pull/7).

Honestly, I don't understand iOS project build structure well enough to find it myself, let alone write code to do it.

Meanwhile, I propose we simply [update the docs](https://github.com/rollbar/rollbar-ios/pull/19) explaining that one might have to update the ```info_file_path``` assignment:.

**Comment by ches** [comment]
Although it's buffered by Xcode until the script finishes, it's nice to get some output in the build log, whether debugging an issue like this or not. Here's a slightly cleaned-up version of the script with a few useful `print`s (and modified with `BUILT_PRODUCTS_DIR` for the `Info.plist` path as @bkobilansky suggests, which works for my projects):

```python
"""
Send dSYM to Rollbar for usable traces in the web UI.

https://rollbar.com/docs/notifier/rollbar-ios/#symbolication-using-dsym-files
"""

import os
import subprocess
import zipfile

ACCESS_TOKEN = 'POST_SERVER_ITEM_ACCESS_TOKEN'

if os.environ['DEBUG_INFORMATION_FORMAT'] != 'dwarf-with-dsym' or os.environ['EFFECTIVE_PLATFORM_NAME'] == '-iphonesimulator':
    print("Not a dSYM-enabled release build, no upload to Rollbar")
    exit(0)

dsym_folder_path = os.environ['DWARF_DSYM_FOLDER_PATH']
dsym_file_name = os.environ['DWARF_DSYM_FILE_NAME']
dsym_file_path = os.path.join(dsym_folder_path, dsym_file_name)
zip_location = '%s.zip' % (dsym_file_path)

print("Zipping dSYM data...")
os.chdir(dsym_folder_path)
with zipfile.ZipFile(zip_location, 'w') as zipf:
    for root, dirs, files in os.walk(dsym_file_name):
        zipf.write(root)

        for f in files:
            zipf.write(os.path.join(root, f))

info_file_path = os.path.join(os.environ['BUILT_PRODUCTS_DIR'],
                              os.environ['INFOPLIST_PATH'])
p = subprocess.Popen('/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" -c "Print :CFBundleIdentifier" "%s"' % info_file_path,
                     stdout=subprocess.PIPE, shell=True)

stdout, stderr = p.communicate()
version, identifier = stdout.split()

print("Trying Info.plist file at {0}".format(info_file_path))
print("Determined bundle version: {0}, identifier: {1}".format(version, identifier))

print("Uploading dSYM data to Rollbar...")
p = subprocess.Popen('curl -X POST "https://api.rollbar.com/api/1/dsym" -F access_token=%s -F version=%s -F bundle_identifier="%s" -F dsym=@"%s"'
                     % (ACCESS_TOKEN, version, identifier, zip_location), shell=True)
p.communicate()
```

This is Python 3-ready whenever Apple updates `/usr/bin/python`, but works in the 2.7 versions from the last few OS X releases too.

**Comment by rivkahstandig3636** [comment]
Is this still an issue?

**Comment by Samuel-Samir** [comment]
It works for me 
 Xcode -> Preferences -> Locations -> Command Line Tools set xcode

reference  : 
https://forum.realm.io/t/cant-install-with-cocoapods-xcode-swift/977/3
