### ISSUE TITLE
Rollbar 1.0.0 - KSSSystemCapabilities.h file not found

### ISSUE THREAD

**Issue by fjbelchi** [rollbar/rollbar-ios#115]
Updating the pod from version 0.2.0 to 1.0.0. KSSystemCapabilities.h file is not found.

<img width="1300" alt="screen shot 2018-08-20 at 09 44 09" src="https://user-images.githubusercontent.com/626713/44326978-a6135a00-a45d-11e8-8102-5942b0604c10.png">

**Comment by rivkahstandig3636** [comment]
Thanks for reporting this @fjbelchi, we'll take a look into it!

**Comment by akornich** [comment]
@fjbelchi, may I ask you to describe you application configuration (as it relates to use of Rollbar pod) in details? I just created a sample app, added use of Rollbar 1.0.0 pod to it and was able to successfully build, run and report a log message to Rollbar. I suspect there could be something specific in your configuration that cases the issue that you reported...

**Comment by fjbelchi** [comment]
Thanks @akornich , I've checked the file and it is inside KSCrash > Recording.

The Podfile has: `platform :ios, '10.0'` and `use_frameworks!` with:
```
pod 'Rollbar', '~> 1.0.0'
pod 'KSCrash'
```

**Comment by akornich** [comment]
@fjbelchi, please, try removing explicit dependency on KSCrash pod from your Podfile...

**Comment by akornich** [comment]
@fjbelchi, also, once you remove "pod 'KSCrash'" line from your Podfile, do not forget to clean your product build and run "pod install" before rebuilding the application.

**Comment by fjbelchi** [comment]
It works! Thanks @akornich
