### ISSUE TITLE
Is there a reason why library should constantly spam "Checking items..." into console? 

### ISSUE THREAD

**Issue by Skogetroll** [rollbar/rollbar-ios#119]
After I've tried to install version 1.1.0 I got 60 messages/minute written into my console. 
Which is not really handy, because I was using the console for own logs and now all I can see is `[Rollbar] Checking items...`

Is there a real reason why it's there? And can it be turned off without going to `RELEASE` config?

**Comment by akornich** [comment]
@Skogetroll , yes, it was enabled for DEBUG builds for development purposes. we can probably remove it by the next release. for now, you can call setReportingRate(1) on RollbarConfiguration to limit it to 1 message per minute.

**Comment by akornich** [comment]
@Skogetroll, or another option could be integrating Rollbar-iOS via CocoaPods so you will not be getting these messages at all...

**Comment by Skogetroll** [comment]
Well, It was integrated via CocoaPods already.

**Comment by akornich** [comment]
Rollbar-iOS is retiring. All the v2.0.0-alpha... releases functionality is already available under GA releases of [Rollbar-Apple](https://github.com/rollbar/rollbar-apple). Including the suppression of the SDK informational logging. Closing it here...
