### ISSUE TITLE
If a user upgrades between the crash and opening the app next, the reported version is incorrect

### ISSUE THREAD

**Issue by brianr** [rollbar/rollbar-ios#12]
In this scenario:
1. User is running version 1.0 and there is a crash
2. User upgrades to 1.1
3. User opens the app and the crash is reported

rollbar-ios will currently report this crash as happening in 1.1 (the version that was running when the crash was reported) rather than 1.0 (the version that was running when the crash happened).

**Comment by rokob** [comment]
This may be possible to resolve with KSCrash as we have more control over the crash reporting, but not sure. We need to handle how the crash gets written to disk in the signal handler, will have to see if we can do that.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
