### ISSUE TITLE
Make crash reporting optional

### ISSUE THREAD

**Issue by marcelofabri** [rollbar/rollbar-ios#134]
A lot of apps already use another solution for crash reports. It would be great to have a way to opt-out from this. 

Currently we roll our own fork to do it, which is not a great solution 😅

**Comment by rokob** [comment]
https://github.com/rollbar/rollbar-ios/blob/master/Rollbar/Rollbar.h#L18,L19

Pass `NO` to `enableCrashReporter`

**Comment by marcelofabri** [comment]
Ideally this would also avoid compiling the crash reporting related code and not embedding `PLCrashReport`.

**Comment by rokob** [comment]
We should provide a logging only build

**Comment by cjwirth** [comment]
Also, including `KSCrash` makes it so Rollbar cannot be used within App Extensions, because it's using app-specific APIs like `[[[UIApplication sharedApplication] delegate] window]` and `UIAlertView`, which has been deprecated for a long time.

**Comment by akornich** [comment]
this improvement is already implemented and available in the context of this SDK's replacement: [Rollbar-Apple](https://github.com/rollbar/rollbar-apple)
