### ISSUE TITLE
Integrating Rollbar inside a framework I get missing required module Rollbar

### ISSUE THREAD

**Issue by philmartin83** [rollbar/rollbar-ios#135]
I’ve integrated the Rollbar iOS framework inside my custom framework, when deploying this to third parties they experience an error “missing required module Rollbar” do you have an examples of how to integrate Rollbar inside a customer framework or how to put Rollbar inside a module.map file. The custom framework is written in swift, is there a swift version of Rollbar.

**Comment by jessewgibbs** [comment]
@akornich could you help out @philmartin83 with this question?

**Comment by akornich** [comment]
@jessewgibbs and @philmartin83 , let me see what I can do...

**Comment by akornich** [comment]
@philmartin83 , are you using Rollbar-iOS via CocoaPods within your own framework?

**Comment by philmartin83** [comment]
@akornich, no I’m not, I’ve tried the CocoaPods route but I get the same error.

**Comment by akornich** [comment]
@philmartin83 , so you are integrating Rollbar-iOS as a framework (not a static lib). Correct?

**Comment by philmartin83** [comment]
Yes that’s correct.

**Comment by philmartin83** [comment]
Would it be better to add as a static library?

**Comment by akornich** [comment]
could be worth trying. if it unblocks your customers until we figure out what prevents integration via the framework to work.

**Comment by philmartin83** [comment]
Ok I’ll do that. Thanks for the speedy responses. I’ll let you know how I get on.

**Comment by philmartin83** [comment]
Ok added it as a static library and it all worked fine I was able build and deploy the sdk and it passed our CI testing.

**Comment by jessewgibbs** [comment]
@philmartin83 great, thanks for letting us know. I’m going to go ahead and close this issue, but let us know if anything else comes up.

**Comment by akornich** [comment]
@philmartin83 , please take a look at this pending PR #137 (or you can check it out in my fork at [](https://github.com/WideSpectrumComputing/rollbar-ios) - all the latest commit named "Examples:...")
