### ISSUE TITLE
The Rollbar.zip's for version 1.4.0 and 1.4.1 don't include the framework

### ISSUE THREAD

**Issue by itsthetaste** [rollbar/rollbar-ios#139]
So when including in Xcode, following your instructions, you get the error "framework not found rollbar" when you try to build.

1.3.0 does include the framework (you can tell because it's ~10MB, whereas 1.4.0 and 1.4.1 are about 30KB).

**Comment by akornich** [comment]
@itsthetaste , please, try again v1.4.1:
[https://github.com/rollbar/rollbar-ios/releases/tag/v1.4.1](https://github.com/rollbar/rollbar-ios/releases/tag/v1.4.1)
I just updated the zip files...

**Comment by akornich** [comment]
@itsthetaste , the v1.4.0 should be also good now:
[https://github.com/rollbar/rollbar-ios/releases/tag/v1.4.0](https://github.com/rollbar/rollbar-ios/releases/tag/v1.4.0)
Thanks for catching it!

**Comment by itsthetaste** [comment]
Cool, I'll check thanks

**Comment by akornich** [comment]
@itsthetaste , btw, did you try including at least one of these releases via CocoaPods?

**Comment by akornich** [comment]
@itsthetaste , I think I figured it out. Xcode 10 changed some build process paths and our  Distribution target's build scripts had to be adjusted. Please, give another try to v1.4.1:
[https://github.com/rollbar/rollbar-ios/releases/tag/v1.4.1](https://github.com/rollbar/rollbar-ios/releases/tag/v1.4.1)

**Comment by akornich** [comment]
@itsthetaste , v1.4.0 is also rebuilt now with the corrected Distribution build scripts:
[https://github.com/rollbar/rollbar-ios/releases/tag/v1.4.0](https://github.com/rollbar/rollbar-ios/releases/tag/v1.4.0)

**Comment by akornich** [comment]
@itsthetaste , did you have a chance to verify the latest fix?
