### ISSUE TITLE
dsym upload build script fails

### ISSUE THREAD

**Issue by respectTheCode** [rollbar/rollbar-ios#14]
I had to use `BUILT_PRODUCTS_DIR` instead of `INSTALL_DIR`.

```python
info_file_path = os.path.join(os.environ['BUILT_PRODUCTS_DIR'], os.environ['INFOPLIST_PATH'])
```

**Comment by s0meone** [comment]
Yes, same here. Thank you, your solution works.

I'm using Xcode 6.4.

**Comment by kshep** [comment]
Duplicate of https://github.com/rollbar/rollbar-ios/issues/11
