### ISSUE TITLE
Filtering exceptions.

### ISSUE THREAD

**Issue by philmartin83** [rollbar/rollbar-ios#142]
Hi, 
This is more of a question, is there a way to filter out certain exceptions from the stack trace when an app crashes. Currently we get every instance of a crash and we would like to filter out only when our SDK crashes an app.

Thanks

**Comment by philmartin83** [comment]
Hey @jessewgibbs

Are there any code examples of this and what are the dictionary keys?

Thanks
Phil

**Comment by jessewgibbs** [comment]
@akornich do you know if there are any examples of using `setCheckIgnoreBlock`?

**Comment by akornich** [comment]
not as far as I know, but it has to be as simple as implementing a block that receives a payload object and returns bool as a result based on custom logic of checking the payload content.

**Comment by philmartin83** [comment]
@akornich I noticed the RollbarNotifier object has a isRoot bool on the initialiser, what does “isRoot” represent, could I use that at all? At the moment we are getting lots of EXC_BAD_ACCESS(SIGBUS) errors coming through via email and slack and when I look at the stack trace there’s no reference to our SDK causing this issue, it always seems to be around GSEventRunModal the graphic service in iOS, which is what the app is based around, we really need to filter these and only have crashes caused by our SDK

**Comment by philmartin83** [comment]
I’ve already done some filtering on the trace to look for only references of our SDK this has already been released just waiting for our partners to integrate, I have one other question though.... EXC_BAD_ACCESS (SIGBUS): Application terminated this error comes through from an app publisher 500 - 600 times a day, are these genuine errors or does Rollbar get triggered if the app is quit via the app switcher. I can’t imagine an app would crash that often with the extensive testing that’s performed.

**Comment by akornich** [comment]
@philmartin83 , could it be that the current filtering implementation occasionally triggers an exception? We have code that invokes `checkIgnore` within `@try` and, then, if catches anything it starts ignoring "bad" `checkIgnore`, hence always transmitting any subsequent payload after that - no filtering attempted...

**Comment by philmartin83** [comment]
Our SDK filtering implementation isn’t in that particular app yet, they do a release every 4 weeks. But I can understand your logic, I see from your backend that that particular crash log as been invoked 90 times by the same device so I’ve muted it from your backend.

**Comment by philmartin83** [comment]
Hi @akornich 

Should the setCheckIgnore block match the Raw JSON that appears on the RollBar website? 
Because its doesn't seem to, I'm currently missing "trace" from the payload if it is supposed to match.

**Comment by akornich** [comment]
Hi @philmartin83 ,
your set checkIgnore implementation should navigate a payload that is constructed out basic data structures: mutable dictionaries and arrays of mostly string. The conversion into JSON happens as the very last step right before transmitting the payload to Rollbar API.
As an example of how to navigate/iterate payload content, RollbarPayloadTruncator.m is a good one:
[https://github.com/rollbar/rollbar-ios/blob/master/Rollbar/RollbarPayloadTruncator.m](https://github.com/rollbar/rollbar-ios/blob/master/Rollbar/RollbarPayloadTruncator.m)

**Comment by akornich** [comment]
@philmartin83 , did RollbarPayloadTruncator.m example help in resolving the issue you are facing?
