### ISSUE TITLE
Improve Swift usage

### ISSUE THREAD

**Issue by retsohuang** [rollbar/rollbar-ios#144]
It's nice to have [Nullability](https://github.com/material-components/material-components-ios/blob/develop/contributing/checklist.md#nullability) and [Swift Overrides and Annotations](https://github.com/material-components/material-components-ios/blob/develop/contributing/checklist.md#swift-overrides-and-annotations) for Swift uses.

**Comment by jessewgibbs** [comment]
@retsohuang thanks for the suggestion.  We'll add this to our backlog.

**Comment by akornich** [comment]
this improvement is already implemented and available in the context of this SDK's replacement: [Rollbar-Apple](https://github.com/rollbar/rollbar-apple)
