### ISSUE TITLE
Crash reports cause "API error: Invalid format. data should be object."

### ISSUE THREAD

**Issue by jessicahsieh** [rollbar/rollbar-ios#145]
Rollbar System Message: https://rollbar.com/wealthsimple/mobile/items/17/
Message occurs when app automatically tries to send a crash report. 

configuration: https://gist.github.com/jessicahsieh/6b31fe7b68dae8dccbc752713fcf0672

**Comment by jessewgibbs** [comment]
@akornich can you close this issue and let @jessicahsieh know once the fix has been released?

**Comment by sterlingwes** [comment]
Which version did this land in?

**Comment by rokob** [comment]
It was merged but not released yet. When you link a PR with an issue it closes the issue when you merge the PR. Sorry about that, I will make a release today.

**Comment by sterlingwes** [comment]
Thanks, looking forward to it!

**Comment by rokob** [comment]
I just pushed v1.5.0

**Comment by sterlingwes** [comment]
Thanks @rokob - can we expect a release for `rollbar-react-native` as well? I'd take a stab at it but the contributing notes don't go over cutting releases

**Comment by rokob** [comment]
Ah yeah sorry I will do that this morning.
