### ISSUE TITLE
XCode 10.2 Beta3

### ISSUE THREAD

**Issue by philmartin83** [rollbar/rollbar-ios#149]
Hi,

I'm currently testing our SDK using swift 5 and XCode 10.2 and we keep seeing a crash that did't appear in the the previous version of XCode or in our SDK?

This seems to be causing a problem according to you crash log below, what is **_kscm_user_getAPI_**, I've done a quick google and is seems to be around the KSCrashMonitor_User.h has anyone experienced this or is this an inaccurate crash because the app seems to be running fine.

I've included a report from the Rollbar back end.

Thanks

Exception Type:  EXC_BAD_ACCESS (SIGBUS)
Exception Codes: KERN_INVALID_TASK at 0x0000000000000010
Crashed Thread:  0

Thread 0 Crashed:
0   libobjc.A.dylib                 0x0000000193e5ef70 objc_msgSend + 16
1   libswiftCore.dylib              0x0000000103b39f48 swift_unexpectedError + 139140
2  MySDK                          0x0000000103981f64 kscm_user_getAPI + 362904
3   MySDK                          0x0000000103989ff8 kscm_user_getAPI + 395820
4   MySDK                          0x000000010393d4b4 kscm_user_getAPI + 81640
5   MySDK                          0x0000000103942d68 kscm_user_getAPI + 104348
6   MySDK                          0x00000001039b6db8 kscm_user_getAPI + 579564
7   MyTestApp                   0x0000000103013560 0x102ff4000 + 128352
8   MyTestApp                   0x0000000103005d50 0x102ff4000 + 73040
9   MyTestApp                   0x000000010300762c 0x102ff4000 + 79404
10  MyTestApp                   0x0000000103004acc 0x102ff4000 + 68300
11  MyTestApp                   0x0000000103007ef8 0x102ff4000 + 81656
12  MyTestApp                   0x0000000103018c94 0x102ff4000 + 150676
13  libdispatch.dylib               0x000000019464fb9c 0x19464d000 + 11164
14  (null) 0x005bb88194651134 0x0 + 25817089560613172
15  (null) 0x00710f819465cf50 0x0 + 31823721583202128
16  (null) 0x00598f0194bdc0fc 0x0 + 25208509880451324
17  (null) 0x005c440194bd6d78 0x0 + 25970471438478712
18  (null) 0x006f680194bd62e8 0x0 + 31358078414578408
19  (null) 0x003ad08196e8abe8 0x0 + 16554803650407400
20  (null) 0x00315001c2918088 0x0 + 13880242348327048
21  (null) 0x0047c80102ffc188 0x0 + 20204630017294728
22  libdyld.dylib                   0x0000000194689050 0x194688000 + 4176

**Comment by rokob** [comment]
I haven't tried Swift 5 yet with the SDK, there is a chance that due to the ABI changes there could be an issue depending on how you are integrating the SDK. Are you using Cocoapods or including the framework directly?

**Comment by philmartin83** [comment]
@rokob I’m integrating the framework directly. But I have seen that you upgraded your rollbar sdk, I’ve put them in today and I’m going to retest, using Xcode 10.2 b3 I don’t know if your 1.5.0 version has many changes that could fix this issue, the Rollbar docs website site is still showing your latest version as 1.4.2 in the pod command.

**Comment by rokob** [comment]
1.5.0 was built with Xcode 10.1 which didn't know about Swift 5. It may solve your problem, but if it doesn't then I can try making a framework build on the new Xcode, but I'm not sold that this is what is wrong. `kscm_user_getAPI` should never get called by our code. That stacktrace even unsymbolicated looks really strange. It might be some corrupted memory. Is this 100% reproducible?

**Comment by philmartin83** [comment]
well its happened twice, but I haven't been able to get it to happen again no matter what I've tried.

**Comment by rokob** [comment]
Any additional info if/when it happens again would be helpful. I can see what I can do to get it to happen. That function really shouldn't get called. It is for a particular type of report sent via KSCrash that we do not use as far as I can tell. I will need to update my Xcode to see if that helps me track it down.

**Comment by philmartin83** [comment]
Ok thanks, If I can make it happen again is there an email I can send the full stack report to if that would help? I can I use the support email on the website and put a reference against it.

**Comment by rokob** [comment]
You can send it to me at: andrew@rollbar.com

**Comment by philmartin83** [comment]
Ok great, if it happens again I’ll email it over, if it doesn’t I’ll update here. I’ll be testing tomorrow and over the weekend.
