### ISSUE TITLE
Reporting to multiple projects

### ISSUE THREAD

**Issue by NeckCracker** [rollbar/rollbar-ios#154]
Is it possible to send reports to multiple projects?
I would like to send different payloads to different projects with different options.

**Comment by akornich** [comment]
@NeckCracker , you can instantiate and use multiple instances of RollbarNotifier that are configured differently. Just make sure only the very first instance initialized as a root.

**Comment by NeckCracker** [comment]
Sorry for the late reply.
Although I can create multiple notifiers with different configs only the root notifier sends the payload. And the root notifier sends them with its own configuration. So in the end every payload is sent with the same root configuration.
