### ISSUE TITLE
Ability to customize client.ios.code_version

### ISSUE THREAD

**Issue by brianr** [rollbar/rollbar-ios#157]
Currently, the value reported as client.ios.code_version always comes directly from the `kCFBundleVersionKey` and is not customizable.

See https://github.com/rollbar/rollbar-ios/blob/master/Rollbar/RollbarNotifier.m#L302

Let's provide a way to override this default and set it to any string value.

**Comment by 00FA9A** [comment]
Can https://github.com/rollbar/rollbar-ios/pull/158/ resolve the issue?

**Comment by akornich** [comment]
@00FA9A , technically, #158 looks like what we need. we just need to finalize on the configuration property name. The PR uses `codeVersion`. We already have `serverCodeVersion` config property. On the notifier side for a payload, we have 3 instances of corresponding `code_version`s: within `data` object, within `server` object and within `client` object.  I would think we want to call it `clientCodeVersion` within the PR #158 and reserve `codeVersion`  for the one that is part of the `data`.
@brianr , @rokob , do you, guys, agree with this?

**Comment by brianr** [comment]
Since this code itself is running on the thing that is the client, I think it's fine to simply call this config param `codeVersion`.

**Comment by akornich** [comment]
@brianr , thank you! I'll merge it as is, then...
