### ISSUE TITLE
Crash Reporting [Question]

### ISSUE THREAD

**Issue by philmartin83** [rollbar/rollbar-ios#166]
Hey,

One of the app publishers has reported their app crashed because of the SDK i work on, their crashlytics report says their app crashed over 7,000 times because of our code base, but Rollbar has only reported 580 instances of this Is there any reason why, does Crashlytics conflict with Rollbar at all?

**Comment by akornich** [comment]
Hi, @philmartin83. I am not familiar with Crashlytics features but from quick reading about it - it looks like they do local crash log analysis as well as on their servers. Could it be that 7,000 number is based on local Crashlytics reports?
Normally, Rollbar-iOS SDK forwards crash logs to Rollbar servers right on the application restart. I would think if there were Internet connectivity problems on restart some crash logs could be lost and not delivered to the Rollbar servers.

**Comment by philmartin83** [comment]
Ok that makes a lot of sense, our sdk is still in beta in this instance so it’s no major issue other then I need to fix stuff I just wondered why we didn’t seem but this answer from you make perfect sense. Thanks for the quick response.
