### ISSUE TITLE
add support for high sierra

### ISSUE THREAD

**Issue by jtoy** [rollbar/rollbar-ios#168]

**Comment by akornich** [comment]
it is currently in works...

**Comment by jtoy** [comment]
I have that running. But it doesn’t work for high sierrra. Please please fix so we can use rollbar for a widely used Mac app.

**Comment by akornich** [comment]
@jtoy (or anyone else interested in using Rollbar-iOS on macOS) would you be able to give a test run to our latest v1.8.0-alpha8 release on both iOS and macOS? The corresponding CocoaPod is also available. Preferably during this week. 
Thank you!

**Comment by jtoy** [comment]
@akornich yes we will test

**Comment by akornich** [comment]
@jtoy, thank you!

**Comment by jtoy** [comment]
we have a version of it working, it looks good so far, but needs more testing. feel free to tr out our awesome app with rollbar support :)  https://share.getcloudapp.com/OAuRKXZ7

**Comment by akornich** [comment]
@jtoy , that is great news. keep me posted on the testing progress. i'll try to address any issues asap.

**Comment by akornich** [comment]
done
