### ISSUE TITLE
Xcode compile error, framework files ignored

### ISSUE THREAD

**Issue by nocodedweb** [rollbar/rollbar-ios#169]
Errors in screenshot:

![xcode-error](https://user-images.githubusercontent.com/20359577/60525310-5de2dc00-9cab-11e9-9e9a-6ed369bdad43.png)

I've tried both the CocoaPods route and manual setup route, added Rollbar directory in Resources in Xcode.

How to resolve?

**Comment by akornich** [comment]
@nocodedweb , please, follow the following steps precisely: [https://docs.rollbar.com/docs/ios#section-manual](https://docs.rollbar.com/docs/ios#section-manual). I just followed them successfully yesterday while setting up my own project. 
Best regards!

**Comment by nocodedweb** [comment]
The section "Developing and building the library" in the docs was what solved my issue.  I wonder if moving this section above the "Logging" section would be more appropriate?  Either way, this solved my issue.  Thanks.
