### ISSUE TITLE
Create tutorial to use with swift

### ISSUE THREAD

**Issue by mika76** [rollbar/rollbar-ios#17]
As a newbie to swift and ios I would love to see how to integrate this.

**Comment by coryvirok** [comment]
Thanks for the feedback, @mika76. We will take a look.

**Comment by Crisfole** [comment]
Hi @mika76 Sorry for the extremely *long* delay. I've created a demo here: https://github.com/crisfole/swiftweather. The README.md contains a textual walkthrough of the process. The last four commits (the ones that are ahead of the original fork's master) are commits that actually *do* the Rollbar integration.

**Comment by mika76** [comment]
Thanks @Crisfole will have a look...
