### ISSUE TITLE
Xcode 7 builds fail due to missing bitcode

### ISSUE THREAD

**Issue by jonah-williams** [rollbar/rollbar-ios#18]
Attempting to build the Rollbar 0.1.5 pod for an iOS device using Xcode 7 fails:
```ld: '~/Library/Developer/Xcode/DerivedData/<...>/Build/Products/Debug-iphoneos/Rollbar.framework/Rollbar' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64```

Looks like resolving this requires an updated PLCrashReporter framework (see also https://opensource.plausible.coop/bugs/browse/PLCR-581).

Are you folks aware of this and working with Plausible Labs on a solution?

**Comment by kshep** [comment]
@jonah-williams We're aware of the issue, tracking progress on PLCrashReporter, and updating our docs in the mean time: https://github.com/rollbar/rollbar-ios/pull/19

**Comment by moski** [comment]
any update on this issue plz? we can't integrate rollbar with our latest iOS project.

**Comment by Crisfole** [comment]
Hi @moski We're still waiting on [PLCrashReporter](https://opensource.plausible.coop/bugs/browse/PLCR-581). Sorry about the delay.

Have you attempted building with bitcode disabled?

**Comment by moski** [comment]
@Crisfole  same issue, it doesn't work. I actually tried with bitcode disabled at first. I guess i have to wait for the update. Thanks.

**Comment by chien** [comment]
@Crisfole Could you please review #26 ?
