### ISSUE TITLE
Carthage error when build framework

### ISSUE THREAD

**Issue by kiroskirin** [rollbar/rollbar-ios#192]
There is an error when using Carthage to build a framework on the iOS platform with version

github "rollbar/rollbar-ios" ~> 1.8

XCode Version 10.3 (10G8)

Here error log

```console
carthage update rollbar-ios --platform iOS
*** Checking out rollbar-ios at "v1.8.1"
*** xcodebuild output can be found in /var/folders/_r/d0zyvbvd6cb6ryq45mk37nm80000gp/T/carthage-xcodebuild.GFhOny.log
*** Downloading rollbar-ios.framework binary at "macOS support, server enforced rate limit and more..."
*** Skipped building rollbar-ios due to the error:
Dependency "rollbar-ios" has no shared framework schemes for any of the platforms: iOS
```

**Comment by kevinmcconnell** [comment]
I just ran into the same issue.  For what it's worth, it build successfully if you use version `v1.7.0`.  However the `v1.8.x` versions seem to no longer include an iOS framework; they only build for macOS.

**Comment by sjmadsen** [comment]
Walking back the commits that occurred after the 1.7.0 release, I think c618f0509024df152298c0b3e7b9421e9dd36671 is the culprit. That's just a catch-up/merge commit, though, so I'll guess that adding macOS support is probably where it started.

**Comment by akornich** [comment]
#196
