### ISSUE TITLE
Carthage Umbrella header for module 'Rollbar' does not include header 'xxx.h'

### ISSUE THREAD

**Issue by kiroskirin** [rollbar/rollbar-ios#193]
There is a warning about

```
Umbrella header for module 'Rollbar' does not include header 'RollbarDeploysManager.h'
```
<img width="289" alt="Screen Shot 2562-08-13 at 17 36 35" src="https://user-images.githubusercontent.com/311686/62935287-eb5c3480-bdf0-11e9-88be-aeda62140ba7.png">

XCode Version 10.3 (10G8)

**Comment by kevinmcconnell** [comment]
Are you including the header files in a bridging header in your project?  This looks like the same error you'll get if you skip that step.

See: https://docs.rollbar.com/docs/ios#section-swift

**Comment by kiroskirin** [comment]
> Are you including the header files in a bridging header in your project? This looks like the same error you'll get if you skip that step.
> 
> See: https://docs.rollbar.com/docs/ios#section-swift

Yep, that true.
