### ISSUE TITLE
Capture Log As Telemetry - Not working? Introducing RollbarLog(...)

### ISSUE THREAD

**Issue by Alarson93** [rollbar/rollbar-ios#206]
I can't tell if I'm doing something wrong or if `setCaptureLogAsTelemetryData` is not working.

Based on some test code found [here](https://github.com/rollbar/rollbar-ios/blob/master/RollbarTests/RollbarConfigurationTests.m), I created a sample function:

```
let string = "log-message-testing"
RollbarTelemetry.sharedInstance()?.clearAllData()
Rollbar.currentConfiguration()?.telemetryEnabled = true
Rollbar.currentConfiguration()?.setCaptureLogAsTelemetryData(true)
RollbarTelemetry.sharedInstance()?.getAllData()
NSLog(string)
print("Foobar")
Rollbar.debug("test")
print("DONE")
```

But when I arrive at the "DONE" print statement - my telemetry array is still empty. I would expect to see either (or both) `log-message-testing` or `Foobar` in my array.

If I manually log an event like:
`Rollbar.recordViewEvent(for: RollbarDebug, element: "Something")`
The "Something" event will be logged.

**My question is**: Why am I not seeing my console/log events in my telemetry data?

Related question - The [Rollbar page for iOS](https://rollbar.com/error-tracking/ios/) seems to allude to a pretty Telemetry section on your event detail (much like how we have a section for the stacktrace). I see the telemetry data including in the raw JSON on the Rollbar website when I log "Something", but I do not see a dedicated telemetry section.

Edit: I'm currently using Rollbar 1.5.2

**Comment by akornich** [comment]
Hi @Alarson93, I'll look into this shortly. As far as I know, there were no changes around the telemetry feature for a long time. Your usage snippet does look legit. I'll have to play with it myself under the debugger...

**Comment by Alarson93** [comment]
Thank you! 
I edited the original post to include the Rollbar version I'm using. I'm going to try updating and see if that helps.

**Comment by akornich** [comment]
Hi @Alarson93, thanks for the updates!
I just ran a slightly modified version of our NSLog capture unit test:
`- (void)testLogTelemetryAutoCapture {
    NSString *logMsg = @"log-message-testing";
    [[RollbarTelemetry sharedInstance] clearAllData];
    Rollbar.currentConfiguration.accessToken = @"[VALID ACCESS TOKEN]";
    Rollbar.currentConfiguration.telemetryEnabled = YES;
    [Rollbar.currentConfiguration setCaptureLogAsTelemetryData:YES];
    // The following line ensures the captureLogAsTelemetryData setting is flushed through the internal queue
    [[RollbarTelemetry sharedInstance] getAllData];
    NSLog(logMsg);
    [Rollbar debug:@"test"];
    
    RollbarFlushFileThread(Rollbar.currentNotifier);

    NSArray *logItems = RollbarReadLogItemFromFile();
    NSArray *telemetryData = [logItems[0] valueForKeyPath:@"body.telemetry"];
    NSString *telemetryMsg = [telemetryData[0] valueForKeyPath:@"body.message"];
    XCTAssertTrue([logMsg isEqualToString:telemetryMsg],
                  @"body.telemetry[0].body.message is %@, should be %@",
                  telemetryMsg,
                  logMsg
                  );
    
    [NSThread sleepForTimeInterval:3.0f];
}
` 
and ot seems to work fine:
![image](https://user-images.githubusercontent.com/1753993/67908930-8e903080-fb3a-11e9-9851-a1ef6e722df7.png)

I did use the latest state (head) of the codebase.

**Comment by akornich** [comment]
@Alarson93 , btw, to your question about the telemetry presentation on the Rollbar Dashboard: it only shows up on the item details level/view and not on the occurrence level/view.

**Comment by Alarson93** [comment]
Hmm. Interesting. I'll translate your example directly to swift (with an appropriate access token) and give it a test. I _should_ see the telemetry data logged.

If I do see the data, I can work towards what my example was - line by line - until something breaks.
If I don't see the data - the issue must have something to do with my project configuration.

I'll post back when after I've done some more testing!
Thank you for taking the time to look into this.

**Comment by akornich** [comment]
@Alarson93 , i just wanted to check on you if you still need some help or we can close this issue...

**Comment by Alarson93** [comment]
@akornich My apologies; I was very busy for the entirety of last week.
I'll have time this afternoon to test the code you posted.

**Comment by akornich** [comment]
@Alarson93 , no problem at all.

**Comment by Alarson93** [comment]
@akornich I'm having some trouble with `RollbarFlushFileThread` and `RollbarReadLogItemFromFile`.

I've searched my workspace (including cocoapods) for those, but I get no results. Consequently I cannot use them.
Are those supposed to be included with the pod or are they part of the sample project and/or unit tests?

**Comment by akornich** [comment]
@Alarson93 , `RollbarFlushFileThread` and `RollbarReadLogItemFromFile` sound like out unity test utility's methods. Let' me double check it...

**Comment by akornich** [comment]
yes, they are part of our unit testing infrastructure and not part of the product codebase.

**Comment by akornich** [comment]
@Alarson93 , please, try this one:

```
        Rollbar.initWithAccessToken("MYTOKEN")
        let logMsg = "log-message-testing"
        RollbarTelemetry.sharedInstance()?.clearAllData()
        Rollbar.currentConfiguration()?.environment = AppConfigurations.environment
        Rollbar.currentConfiguration()?.logLevel = "debug"
        Rollbar.currentConfiguration()?.telemetryEnabled = true
        Rollbar.currentConfiguration()?.setCaptureLogAsTelemetryData(true)      
  
        NSLog(logMsg)
        Rollbar.debug("test")
        Rollbar.debug("test")
        
        //block the app for 5 sec before exiting it
        print("DONE")
        //check you project RollbarDashboard for the new debug items 
        //with the logMsg captured as part of the telemetry data
```

**Comment by Alarson93** [comment]
@akornich 

I ran the code - exactly as you have it - and left the app open for about 5 minutes. (I didn't have any reason to close it.)

It took about 5 minutes for the events to appear in my Items list. I see both of the "test" debug events (both recorded at 4:28 pm local time), but I still don't see any telemetry data. I looked at each occurrence and neither contain the telemetry data in their raw JSON bodies.

Here is the first raw body:
```
{
  "body": {
    "message": {
      "body": "test"
    }
  }, 
  "uuid": "REDACTED", 
  "language": "objective-c", 
  "level": "debug", 
  "timestamp": 1573511313, 
  "custom": {}, 
  "environment": "debug", 
  "framework": "ios", 
  "client": {
    "user_ip": "REDACTED", 
    "timestamp": 1573511312, 
    "ios": {
      "device_code": "x86_64", 
      "app_name": "REDACTED", 
      "code_version": "1", 
      "bundle_identifier": "REDACTED", 
      "short_version": "1", 
      "ios_version": "13.1"
    }
  }, 
  "platform": "ios", 
  "notifier": {
    "version": "1.5.2", 
    "name": "rollbar-ios"
  }, 
  "metadata": {}
}
```

I updated Rollbar to the latest version which required me to change `...setCaptureLogAsTelemetryData(true)` to `...captureLogAsTelemetryData = true`.
I am now seeing telemetry show up in the JSON body, but "log-message-testing" was not included.

Here is the JSON:
```
{
  "body": {
    "message": {
      "body": "test"
    }
  }, 
  "uuid": "REDACTED", 
  "language": "objective-c", 
  "level": "debug", 
  "person": {
    "username": "", 
    "id": "", 
    "email": ""
  }, 
  "timestamp": 1573512408, 
  "server": {
    "code_version": "", 
    "root": "", 
    "host": "", 
    "branch": ""
  }, 
  "environment": "debug", 
  "platform": "client", 
  "client": {
    "user_ip": "REDACTED", 
    "timestamp": 1573512406, 
    "ios": {
      "device_code": "x86_64", 
      "app_name": "REDACTED", 
      "code_version": "1", 
      "bundle_identifier": "REDACTED", 
      "short_version": "1", 
      "os_version": "13.1", 
      "os": "iOS"
    }
  }, 
  "requestId": "", 
  "framework": "ios", 
  "custom": {}, 
  "notifier": {
    "version": "1.9.1", 
    "name": "rollbar-ios", 
    "configured_options": {
      "developerOptions": {
        "transmit": true, 
        "logPayloadFile": "rollbar.payloads", 
        "logPayload": false, 
        "enabled": true
      }, 
      "destination": {
        "environment": "debug", 
        "endpoint": "https://api.rollbar.com/api/1/item/", 
        "accessToken": "REDACTED"
      }, 
      "telemetry": {
        "captureConnectivity": false, 
        "enabled": true, 
        "captureLog": true, 
        "maximumTelemetryData": 10, 
        "vewInputsScrubber": {
          "enabled": true, 
          "scrubFields": [], 
          "whitelistFields": []
        }
      }, 
      "custom": {}, 
      "person": {
        "username": "", 
        "id": "", 
        "email": ""
      }, 
      "dataScrubber": {
        "enabled": true, 
        "scrubFields": [], 
        "whitelistFields": []
      }, 
      "loggingOptions": {
        "codeVersion": "", 
        "captureIp": "CaptureIpFull", 
        "crashLevel": "error", 
        "framework": "ios", 
        "maximumReportsPerMinute": 60, 
        "requestId": "", 
        "logLevel": "debug"
      }, 
      "httpProxy": {
        "proxyUrl": "", 
        "enabled": false
      }, 
      "server": {
        "host": "", 
        "root": "", 
        "branch": "", 
        "codeVersion": ""
      }, 
      "notifier": {
        "version": "1.9.1", 
        "name": "rollbar-ios"
      }, 
      "httpsProxy": {
        "proxyUrl": "", 
        "enabled": false
      }
    }
  }, 
  "metadata": {}
}
```

**Comment by akornich** [comment]
Yes, i think your significant delay in seeing the new items showing up in the dashboard is due to ongoing work on the backend that introduces unusual delays (I just noticed them too). But this should be resolved soon.
As far as telemetry issue goes: I just modified one of our sample apps for macOS to enable NSLog capture within the Telemetry data. Here is one sample item: https://rollbar.com/Rollbar/rollbar-ios/items/139/
I'll be checking in the updated sample soon and will post a link to it here.

**Comment by akornich** [comment]
@Alarson93 , here is the updated sample app: https://github.com/WideSpectrumComputing/rollbar-ios/tree/master/Examples/macOScmdTool_Workspace

**Comment by akornich** [comment]
The SDK usage looks like this:
```
int main(int argc, const char * argv[]) {
    @autoreleasepool {
        // configure Rollbar:
        RollbarConfiguration *config = [RollbarConfiguration configuration];
        config.environment = @"samples";
        config.telemetryEnabled = YES;
        config.maximumTelemetryData = 20;
        config.captureLogAsTelemetryData = YES;
        [Rollbar initWithAccessToken:@"NNNN" configuration:config];
        
        NSLog(@"Hello, World!");
        NSLog(@"See you in Telemetry!");

        @try {
            [BuggyClass callTroubleMaker];
        }
        @catch (NSException *exception) {
            
            [Rollbar critical:@"Caught an exception while invoking BuggyClass"
                    exception:exception
             ];
        }

        
        int i = 10;
        while (0 < i--) {
            [Rollbar info:@"Message from macOScmdTool"];
            [NSThread sleepForTimeInterval:1.0f];
        }
    }
    return 0;
}
```

**Comment by Alarson93** [comment]
Unfortunately I am greeted with "Access not allowed" when I visit https://rollbar.com/Rollbar/rollbar-ios/items/139/.

That aside - I added a manual telemetry event to the previous test code while I was waiting for you to post the other link.

```
      Rollbar.initWithAccessToken("REDACTED")
      let logMsg = "log-message-testing"
      RollbarTelemetry.sharedInstance().clearAllData()
      Rollbar.currentConfiguration().environment = AppConfigurations.environment
      Rollbar.currentConfiguration().logLevel = "debug"
      Rollbar.currentConfiguration().telemetryEnabled = true
      Rollbar.currentConfiguration().captureLogAsTelemetryData = true
        
      NSLog(logMsg)
        
      Rollbar.recordViewEvent(for: .debug, element: "MYEVENTTEST")
        
      Rollbar.debug("test")
      Rollbar.debug("test")

      //block the app for 5 sec before exiting it
      print("DONE")
      //check your project RollbarDashboard for the new debug items
      //with the logMsg captured as part of the telemetry data
```

This resulted in MYEVENTTEST being recorded in the JSON.
```
{
  "body": {
    "message": {
      "body": "test"
    }, 
    "telemetry": [
      {
        "body": {
          "element": "MYEVENTTEST"
        }, 
        "source": "client", 
        "timestamp_ms": "1573515620732", 
        "type": "view", 
        "level": "debug"
      }
    ]
  }, ...(the rest was omitted for brevity)
```

So - it appears that I have Telemetry (in general) working, but the log capture still is not working.

(More good news too - it seems like my events are appearing much faster now!)

**Comment by akornich** [comment]
Here is a snapshot of the page that you can not see on item level:
![image](https://user-images.githubusercontent.com/1753993/68634596-d7d17000-04aa-11ea-9a69-4be931c99275.png)
and on occurrence level:
![image](https://user-images.githubusercontent.com/1753993/68634688-2a129100-04ab-11ea-8865-b7f2c42248ac.png)
![image](https://user-images.githubusercontent.com/1753993/68634734-46163280-04ab-11ea-89e2-4a1db590bc51.png)

**Comment by akornich** [comment]
@Alarson93 , that is good news that you can see other telemetry events! you mentioned, that you are using v1.5.2 of the SDK. we are at v1.9.1 now. can you give it a try?

**Comment by akornich** [comment]
oops, it looks like you already tried the upgrade to the latest. Could it be that you have some sort of build settings that "suppress" NSLog messages? When you run the test app do you see the NSLog messages in the output window? 
Sorry for the very basic questions, but I am honestly running out of ideas regarding why you can not see the nslogs while it seems like your use of the SDK looks valid to me.

**Comment by akornich** [comment]
@Alarson93, one more thing to verify, please, make sure in the files where you make your NSLog(...) calls, you also have `RollbarTelemetry.h` imported AFTER `#import <Foundation/Foundation.h>`

**Comment by Alarson93** [comment]
@akornich 

I do see the NSLog messages in my console/output window. 

I don't think I have any log suppression. I've done [this](https://stackoverflow.com/questions/37800790/hide-strange-unwanted-xcode-logs) on other projects, but that flag in not assigned to this particular project.

And no offense taken; the basics are easy to overlook, so it is completely reasonable to ask those questions! :)

My imports are as follows (keep in mind that this is a Swift file):
```
import Foundation
import IQKeyboardManagerSwift
import Droar
import Rollbar
import SVProgressHUD
import OHHTTPStubs
```

That said - **I think I found the cause**. It seems the issue is calling NSLog from Swift code.
I did all of the setup in Swift, but called a `testRollbar` function from an Objective-C class I made.

So it looks like this:

AppConfigurations.swift
```
...some code...

    static func setupRollbar() {
      Rollbar.initWithAccessToken("8727fda55f824e1aac58c38e335e30ee")
      RollbarTelemetry.sharedInstance().clearAllData()
      Rollbar.currentConfiguration().environment = AppConfigurations.environment
      Rollbar.currentConfiguration().logLevel = "debug"
      Rollbar.currentConfiguration().telemetryEnabled = true
      Rollbar.currentConfiguration().captureLogAsTelemetryData = true

      TestThing.testRollbar()

      Rollbar.debug("test")
      Rollbar.debug("test")
    }

...some code...
```

TestThing.m
```
#import "TestThing.h"
#import <Rollbar/Rollbar.h>

@implementation TestThing

+ (void) testRollbar {
    NSString * logMsg = @"log-message-testin2g";
    NSLog(logMsg)
}

@end
```

This resulted in the console Telemetry information being shown on my Item page and being included in the raw JSON on the occurrence page.

**Comment by akornich** [comment]
Now it all starts making sense:
we define NSLog replacement as 
`#define NSLog(args...) [RollbarTelemetry NSLogReplacement:args];`
within RollbarTelemetry.h. That is how NSLog(...) calls get "redirected" into the Rollbar Telemetry capture.
So, the Objective-C preprocessor does not seem to affect Swift source code (which is sort of expected :)). 
I guess that means we can not support NSLog capture (as additional telemetry data) when the SDK is used from Swift. At least at the moment.
We did discuss the possibility of making  Swift native SDK here at Rollbar on a couple of occasions.
But as understand so far we did not see enough (if at all) demand for it. 
However, I am not even sure right now if there is an alternative way in Swift to "intercept" or "redirect" NSLog calls content somehow.

**Comment by akornich** [comment]
@Alarson93 , thanks a lot for actively participating in the investigation of this issue and for bringing it up!

**Comment by akornich** [comment]
BTW, one quick workaround solution could be if introduce something like RollbarLog(...) public function that would internally call NSLog(...) and capture the logged data as Rollbar Telemetry data. But that would imply that you will have to replace all your current NSLog(...) with RollbarLog(...) calls codebase wide.
@Alarson93 , would you like to go this route? I could probably make it available in the upcoming release sometime this week.

**Comment by Alarson93** [comment]
@akornich 

Thank you very much for clarifying how the logs are intercepted.

My original hope was that collecting the log leading up to the crash could probably give me some extra pointers as to what is going on when the crash happens. But, after thinking it over, this could be bad for data security. For example, if I print out an auth token (or a name, email address, etc) to my log - I would hate to see that get uploaded to Rollbar in the event of a crash.

Most of my logs are print statements (as opposed to NSLogs) anyways, so I would need to replace everything with NSLog (if ever fixed for Swift) or the custom `RollbarLog`.

So - collecting any arbitrary log _could_ result in private data being saved to a crash log on Rollbar. Consequently this is probably not the best approach.

I think I'm just going to manually log my events using the appropriate Telemetry functions. Fortunately we were able to get those working over the course of this discussion! 

Lastly - no problem. Community involvement is one of the key benefits of open source code :)
I'm going to mark this thread as closed as I now understand what was wrong and have a viable workaround (just manually logging events OR creating a custom logging function).

Side Note:
I suspect that it would be challenging for you to handle prints as it sounds like they are functionally different. (This is just a guess though. I haven't dug in very far.)
Maybe this wouldn't be an issue if you we created a global project function `print` which calls print + the Rollbar function. This would likely be very similar to what you do with NSLogs. Just food for thought.
https://stackoverflow.com/questions/43287231/should-i-release-an-app-to-the-app-store-with-print-statements-in-it

**Comment by akornich** [comment]
@Alarson93 , we do provide data scrubbing functionality for actual payloads as well as for auxiliary telemetry data. It could be used for masking out private/secret data chunks. However, it works on per data field/element basis (basically masking out the whole value of the field). 
In your specific scenario of masking out some of the similar fields' (i.e. `body.telemetry.body.message`) values conditionally, you may want to try implementing your own payload transform callback that would be applied to every (otherwise-) final version payload where you can watch the NSLog telemetry messages and mask the ones (or their portions) that have secret/private data. For example, if you have a custom category prefix for each NSLog message (like AUTHENTICATION or  LOGIN, etc.) you can mask out or remove only those from the telemetry data of a payload.

**Comment by akornich** [comment]
BTW, RollbarLog(...) will be available in v1.10.0 release (most likely coming out tomorrow)

**Comment by Alarson93** [comment]
Awesome; I'll check that out once it is released. 

Thank you!

**Comment by akornich** [comment]
@Alarson93 , v1.10.0 is out.

**Comment by Alarson93** [comment]
I gave it a quick try, but no luck.

<img width="1533" alt="Screen Shot 2019-11-14 at 4 40 56 PM" src="https://user-images.githubusercontent.com/16312918/68902419-dfd51e00-06fd-11ea-8309-826827bd55fb.png">

**Comment by akornich** [comment]
@Alarson93 , thanks for giving it a try. I guess there is always something new to learn about Swift interop. I think this explains the issue: https://stackoverflow.com/questions/39989081/issue-with-nslog-with-swift-3/39989236
I guess we should change RollbarLog() signature to take in just a NSString instance instead of variadics

**Comment by akornich** [comment]
this improvement (or its equivalent) will be implemented and available in the context of this SDK's replacement: [Rollbar-Apple](https://github.com/rollbar/rollbar-apple)
