### ISSUE TITLE
Usage Question: How to use the rollbar sdk using swift

### ISSUE THREAD

**Issue by lohithkorp** [rollbar/rollbar-ios#208]
I have gone through the documentation of rollbar and I see that it is straight forward to add rollbar sdk into an iOS project but how to implement logging using Swift? There are only Objective-C examples. 

Is there a separate documentation for Swift? please help.

**Comment by akornich** [comment]
Hi @lohithkorp, all the documentation available for Objective-C is 100% applicable to using Rollbar-iOS SDK with Swift. However, with Swift, this extra steps are absolutely critical: [https://docs.rollbar.com/docs/ios#section-swift](https://docs.rollbar.com/docs/ios#section-swift)
All the Objective-C code samples would work in Swift - just use Swift syntax instead: all the same types, properties, methods, and arguments are available when used from Swift.

**Comment by lohithkorp** [comment]
Thanks! :)
Yes, I have noticed the extra steps on the documentation but was wondering if there are no swift syntax examples.

**Comment by akornich** [comment]
@lohithkorp , yes, we currently do not have code snippets in swift within the documentation. Historically, the SDK started as pure Objective-C library so the documentation still reflects that. I, personally, think the syntax translation from Objective-C to Swift should be very straightforward for the SDK usage. But if there are enough requests for the Swift specific code samples we may try to add them.
