### ISSUE TITLE
Add Swift Package Manager support

### ISSUE THREAD

**Issue by kelvinlauKL** [rollbar/rollbar-ios#212]
Hey there,

I've been trying to use the Swift Package Manager to handle fetching my dependencies, and there seems to be a little configuration needed from Rollbar to get that set up for SPM. 

<img width="635" alt="Screen Shot 2019-11-01 at 12 56 49 PM" src="https://user-images.githubusercontent.com/11384608/68041503-172bdf80-fca7-11e9-8dfe-4bc99d1d5a73.png">

Example Package.swift from the `apollo-ios` framework: https://github.com/apollographql/apollo-ios/blob/master/Package.swift

**Comment by akornich** [comment]
Hi Kevin, we never officially supported the Swift Package Manager (only CocoaPods and Carthage, for now).
Should we consider this as an official request for the Swift Package Manager support? Can you use the SDK as a git submodule or via Cocoapods or Carthage for now?

**Comment by kelvinlauKL** [comment]
All our other dependencies are hosted on SPM right now, so we want to keep that consistent. Would appreciate this being considered as an official request. 

Thank you for the quick response.

**Comment by akornich** [comment]
@kelvinlauKL , thanks! I'll look into the support of SPM. I'll try to add it by the end of this month.

**Comment by sjmadsen** [comment]
SwiftPM support is broken in the current release. I've tried changing some things in `Package.swift`, but I can't get past an error where the build system can't locate `KSCrashReportFilter.h` when it's included from the `Rollbar.h` public header.

That public header seems possibly not quite right, too. I interpret the SwiftPM docs as saying the `publicHeadersPath` should be a place where all of the public headers are found, not just included in a giant umbrella header.

**Comment by akornich** [comment]
@sjmadsen , you are absolutely correct in your observations. Except, we never claimed yet the official support of SwiftPM :) As you can see this work item was never resolved (it is on-hold for now).
To complete implementation for SwiftPM support we either need to have KSCrash dependency to officially support SwiftPM or to drastically change the way we are integrating it into our repo. Since KSCrash is not SwiftPM compatible yet and its public header files that we use are scattered all over its folder structure we can not complete this item.
Since we probably can not count on KSCrash support for SwiftPM anytime soon, we will probably take the other alternative of integrating it into our product in some other way that would make SwiftPM support actually doable.

**Comment by akornich** [comment]
The SwiftPM integration is available on the vNext-2.0.0 via RllbarCommon, RollbarDeploys and RollbarNotifier packages and without KSCrash integration (at least for now)

**Comment by arthurschiller** [comment]
I am still experiencing some issues.
Setup is: .package(name: "RollbarSDK", url: "https://github.com/rollbar/rollbar-ios", .branch("vNext-2.0.0"))

Xcode 12.0 (no beta), iOS with Minimum Target iOS 13.

The target dependencies are:
.product(name: "RollbarCommon", package: "RollbarSDK")
.product(name: "RollbarDeploys", package: "RollbarSDK")
.product(name: "RollbarNotifier", package: "RollbarSDK")

RollbarCommon and RollbarDeploys are working but I am getting compile errors for Rollbar Notifier.

<img width="286" alt="Screenshot 2020-09-24 at 12 45 29" src="https://user-images.githubusercontent.com/3637723/94135691-1b835d00-fe64-11ea-93d9-0d24afa70f93.png">
<img width="1372" alt="Screenshot 2020-09-24 at 12 45 33" src="https://user-images.githubusercontent.com/3637723/94135717-2211d480-fe64-11ea-9d86-42e09a556824.png">

**Comment by akornich** [comment]
@arthurschiller , when you follow the "Previous definition is here" where does it lead you to?

**Comment by akornich** [comment]
@arthurschiller , v2.0.0-alpha13 is out. please, try it.

**Comment by arthurschiller** [comment]
Thanks @akornich – I am currently on vacation though. Will definitely test it once I get back.

**Comment by akornich** [comment]
this improvement is already implemented and available in the context of this SDK's replacement: [Rollbar-Apple](https://github.com/rollbar/rollbar-apple)
