### ISSUE TITLE
Can't use Rollbar in extension

### ISSUE THREAD

**Issue by deni2s** [rollbar/rollbar-ios#247]
I tried to implement Rollbar into app action extension and it isn't compiling because of this error in Xcode in KSCrashReportSinkEmail.m line 140

> 'sharedApplication' is unavailable: not available on iOS (App Extension) - Use view controller based solutions where appropriate instead.

**Comment by akornich** [comment]
@deni2s , would you be able to post here a repro project for this compilation error?

**Comment by deni2s** [comment]
@akornich sorry, but no, don't have time for that, and project I am working on is under NDA. 
The issue is that app extensions shouldn't access UIApplication.shared object, so it's not compiling (even if there are ways to avoid that, like described here https://medium.com/@rob.jonson/swift-how-to-use-unsafe-code-in-a-framework-used-by-extensions-50a0705788f2

**Comment by akornich** [comment]
@deni2s , btw, this one also looks like an issue that can be only fixed on the KSCrash side (if I understand the issue correctly).

**Comment by deni2s** [comment]
@akornich, yes, it seems that way.

**Comment by akornich** [comment]
@deni2s, this issue should not be a problem in the context of this SDK's replacement: [Rollbar-Apple](https://github.com/rollbar/rollbar-apple). It has an optional dependency on KSCrash. Also, KSCrash went through some recent updates as well, so you may want to try the new SDK even with the optional KSCrash module enabled.
