### ISSUE TITLE
Nullability

### ISSUE THREAD

**Issue by charlieMonroe** [rollbar/rollbar-ios#27]
Hi there,

are there any plans on updating the Rollbar for iOS framework? Nullability APIs have been around for over a year now, not to mention light-weight generics. We've migrated all of our code to Swift and dealing with Rollbar framework as it is now is not pretty.

Thanks! Charlie

**Comment by rokob** [comment]
Closing this as this will be taken care of by the v1 release: https://github.com/rollbar/rollbar-ios/milestone/1 https://github.com/rollbar/rollbar-ios/milestone/2
