### ISSUE TITLE
Build failed due to reference ambiguous

### ISSUE THREAD

**Issue by retsohuang** [rollbar/rollbar-ios#273]
I found out the enum of `RollbarSource.Client` will cause a conflict with `InstantSearchClient`'s `Client` class since v1.12.0, any suggestions?

Env:
Xcode version: 11.4.1
CocoaPods: 1.9.1

Demo project:
[RollbarBug.zip](https://github.com/rollbar/rollbar-ios/files/4554289/RollbarBug.zip)

**Comment by akornich** [comment]
@retsohuang , thanks for reporting the issue. I guess we will have to rename the enum members as RollbarClinetSource and RollbarServerSource. How about this plan?

**Comment by akornich** [comment]
already available on vNext-2.0.0 branch

**Comment by akornich** [comment]
@retsohuang , did you have a chance to check out our v2 alpha release? 
Available at https://github.com/rollbar/rollbar-ios/releases/tag/v2.0.0-alpha13 
and on Cocoapods as RollbarNotifier
and on SwiftPM

**Comment by retsohuang** [comment]
@akornich Just tested `v2.0.0-alpha13` works fine, thanks.

**Comment by akornich** [comment]
@retsohuang , thanks for the update! Please, feel free to provide feedback regarding the new SDK API in v2. Anything you would like to change or improve even further? We are going to promote it beta within days from now...

**Comment by akornich** [comment]
this problem is already fixed and available in the context of this SDK's replacement: [Rollbar-Apple](https://github.com/rollbar/rollbar-apple)
