### ISSUE TITLE
Ability to set custom data in `RollbarConfiguration` is unavailable

### ISSUE THREAD

**Issue by pauarmada** [rollbar/rollbar-ios#296]
I would like to be able to set a value which is supposed to be attached to all the Rollbar events generated by our App. I used to be able to do this before using the following syntax
```
Rollbar.currentConfiguration()?.setValue(value, forUndefinedKey: key)
```

However, the recent release has this code block commented out
https://github.com/rollbar/rollbar-ios/blob/1c9da63c6407328e6ccb4229d6a581ca0f119c99/Rollbar/Notifier/RollbarConfiguration.m#L625-L637

Is there an alternative way to set this which I am missing?

Thanks

**Comment by akornich** [comment]
@pauarmada , we will be deprecating RollbarConfiguration in favor of RollbaConfig. Please, use:
`Rollbar.currentConfiguration()?.asRollbarConfig()?.customData = ["someKey": "someValue", ];`
to set custom key-values.

**Comment by pauarmada** [comment]
Awesome! Thanks!
