### ISSUE TITLE
[Question]Is there a `rollbarConfig.environemnt`?

### ISSUE THREAD

**Issue by tomoki69386** [rollbar/rollbar-ios#311]
Hi, thanks for the rollbar!

```Swift
let configuration = RollbarConfiguration()
configuration.environment = "Production"
````

How do I set up `configuration.environment = "Production" ` with the V2 `RollbarConfig?

**Comment by akornich** [comment]
@tomoki69386, that would be `rollbarConfig.destination.environment = "Production"`
In v2, RollbarConfig groups settings into logically related "sub-configs": https://github.com/rollbar/rollbar-ios/blob/vNext-2.0.0/RollbarNotifier/Sources/RollbarNotifier/include/RollbarConfig.h

**Comment by akornich** [comment]
@tomoki69386, v2.0.0-alpha12 was just published. It has some improved Swift interface.
Feedback is very welcome!

**Comment by tomoki69386** [comment]
@akornich 

Thank you!
I will continue to use Rollbar.

**Comment by akornich** [comment]
@tomoki69386, sounds good! Happy Rollbarring! And let us know if you would like to see some changes/improvements to the SDK.

**Comment by akornich** [comment]
looks like we can close due to long inactivity
