### ISSUE TITLE
module.modulemap causing build fail

### ISSUE THREAD

**Issue by hzeraat2** [rollbar/rollbar-ios#318]
In **rollbar-react-native version 0.8.1** this file [module.modulemap](https://github.com/rollbar/rollbar-ios/blob/7e0967193aab81e954967bc05b3e301414da76e9/RollbarSwiftPM/module.modulemap) seems to be causing the build to fail: 

We are using **react-native version 0.60.5**

```
node_modules/rollbar-react-native/ios/rollbar-ios/RollbarSwiftPM/module.modulemap:1:8: error: redefinition of module 'Rollbar'
module Rollbar {
```
![Screenshot 2020-09-08 at 13 57 37](https://user-images.githubusercontent.com/11328610/92479620-ac5b0700-f1db-11ea-93cd-5f2c962b8545.png)

**Comment by hzeraat2** [comment]
Please advise!

**Comment by akornich** [comment]
@hzeraat2 , SwiftPM is not officially supported by Rollbar-iOS SDK pre-v2 version releases (due to its SwiftPM incompatible dependencies). Please, do not include RollbarSwiftPM project into your solutions (it was an experimental project attempting to workaround the dependencies problem - but with no success). SwiftPM will be supported in the upcoming v2 release that is currently in its [alpha-phase](https://github.com/rollbar/rollbar-ios/releases/tag/v2.0.0-alpha12).

**Comment by hzeraat2** [comment]
Thank you @akornich for the comments, I think RollbarSwiftPM has been used in the latest release of **rollbar-react-native** as well. We are trying to use version **rollbar-react-native version 0.8.1** do you happen to know which version is more stable for us to use?  
Thanks

**Comment by akornich** [comment]
@hzeraat2 , correct, rollbar-react-native does use rollbra-ios SDK as its dependency but not via SwiftPM (i think, it is used as a git submodule so that RollbarSwiftPM is not "activated").

**Comment by akornich** [comment]
@hzeraat2 , i think if you make sure that you do not directly reference or include RollbaSwiftPM into any of your build targets - you should be able to build it with no problem.

**Comment by hzeraat2** [comment]
We found a problem to this solution. Basically in Xcode we should adjust header search to avoid recursion.
So all occarances of _"$(SRCROOT)/../node_modules/rollbar-react-native/ios/**"_ should become:						**"$(SRCROOT)/../node_modules/rollbar-react-native/ios"**

**Comment by akornich** [comment]
@hzeraat2 , that makes sense. can we close the issue?
