### ISSUE TITLE
Umbrella header for module 'Rollbar' does not include header 'X'

### ISSUE THREAD

**Issue by reidmain** [rollbar/rollbar-ios#32]
We get a number of warnings when including Rollbar as a dependency for our application because the umbrella header for the module is not including all public header files.

```
Umbrella header for module 'Rollbar' does not include header 'RollbarFileReader.h'
Umbrella header for module 'Rollbar' does not include header 'RollbarFramework.h'
Umbrella header for module 'Rollbar' does not include header 'RollbarLogger.h'
Umbrella header for module 'Rollbar' does not include header 'RollbarNotifier.h'
Umbrella header for module 'Rollbar' does not include header 'RollbarReachability.h'
Umbrella header for module 'Rollbar' does not include header 'RollbarThread.h'
```

**Comment by reidmain** [comment]
And speak of the devil it already looks like there is a PR up to fix this https://github.com/rollbar/rollbar-ios/pull/31

**Comment by reidmain** [comment]
It looks like https://github.com/rollbar/rollbar-ios/pull/35 was landed which actually causes the warnings again.

**Comment by rokob** [comment]
This will be resolved by our new v1 release because the issue here is related to PLCrashReporter and we are planning to move to KSCrash which should fix this.
