### ISSUE TITLE
Warning payloads are reported as info payloads.

### ISSUE THREAD

**Issue by mattmapadmi** [rollbar/rollbar-ios#323]
https://github.com/rollbar/rollbar-ios/blob/6930cbd1119599c3c0ed496e25493ef9692dfdb1/Rollbar/Notifier/RollbarFacade.m#L169-L185

The 3 Warning log methods all call the `info` log function. Is this intended behaviour, or should they be calling

`+ (void)warning:(NSString*)message exception:(NSException*)exception data:(NSDictionary*)data context:(NSString*)context` ?

**Comment by akornich** [comment]
yes, correct. @mattmapadmi , thanks for catching it! I'll be issuing a fix today/tomorrow.
