### ISSUE TITLE
Mach-O Linker error

### ISSUE THREAD

**Issue by mayur8657** [rollbar/rollbar-ios#33]
"_OBJC_CLASS_$_PLCrashReportTextFormatter", referenced from:
      objc-class-ref in libRollbar.a(Rollbar.o)
  "_OBJC_CLASS_$_PLCrashReport", referenced from:
      objc-class-ref in libRollbar.a(Rollbar.o)
  "_OBJC_CLASS_$_PLCrashReporter", referenced from:
      objc-class-ref in libRollbar.a(Rollbar.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Just updated to v0.2.0

**Comment by ezarowny** [comment]
How are you including Rollbar.framework and CrashReporter.framework?

**Comment by mayur8657** [comment]
Using Pod

**Comment by mayur8657** [comment]
@ezarowny Any suggestion or solution?

**Comment by ezarowny** [comment]
Can you run `lipo -info` against the binary inside of CrashReporter.framework? I'd be curious to see what slices it includes.

**Comment by ezarowny** [comment]
Oh! Could you also tell me what version of Xcode you are using?

**Comment by mayur8657** [comment]
Xcode version 8.2

**Comment by ezarowny** [comment]
Can you run the lipo command above against the binary inside of the Rollbar.framework and the Crashreporter.framework?

**Comment by Jerome1210** [comment]
I've the issue with Xcode 8.3.2 cocoapod version 1.1.1.
Any update?

**Comment by Jerome1210** [comment]
I fix the issue by replacing the original PLCrashReporter to [v1.2](https://www.plcrashreporter.org/download) 

ref: https://github.com/rollbar/rollbar-ios/pull/44

**Comment by rokob** [comment]
I am going to add this to our v1 milestone as we are working on a update to this library that will resolve this issue by using a different crash reporting framework. Sorry for the delay on this. I'd rather wait for that than work out the details of v1.2 in the short term.
