### ISSUE TITLE
Error if archiving Mac OS app (Xcode 12.2, Mac OS Big Sur)

### ISSUE THREAD

**Issue by ulian-onua** [rollbar/rollbar-ios#334]
I get an error if trying to archive Mac OS app with Rollbar v. 1.12.11 (seems to be the latest one) that installed through CocoaPods. I think it might be related to new Silicon CPUs. 

Here is the screenshot with error:

![image](https://user-images.githubusercontent.com/15073398/99271219-81221300-282f-11eb-9354-4b2233031a3e.png)

The error is:  **Use of undeclared identifier 'kCFCoreFoundationVersionNumber_iOS_8_x_Max** in ...Pods/Rollbar/KSCrash/Source/KSCrash/Recording/Tools/KSObjC.c:198:54:

@akornich any ideas how to fix it?
Thanks.

**Comment by ulian-onua** [comment]
@akornich I've just tried `pod 'Rollbar', '1.12.14'` and can report that the error isn't fixed.

**Comment by akornich** [comment]
@ulian-onua, thanks a lot for giving it a try! I gave up trying to fix it on our side by manipulating our build settings to work around this problem. The actual fix needs to be happening within the KSCrash codebase. Let's wait for that.
Meantime, you may want to try our new SDK [rollbar-apple](https://github.com/rollbar/rollbar-apple) that makes third party crash reporting components optional (at build-time and at run-time) and currently provides integrations with optional KSCrash and PLCrashReporter (as another optional alternative to KSCrash). Officially it is in Alpha state now and we are getting ready to promote it to Beta anytime soon, but I personally consider it already be as a stable Beta (if not even general release) by now. We really just missing the updated public detailed documentation for the SDK to be fully released. However, the basic usage instructions are already publicly [available](https://docs.rollbar.com/docs/apple). Including a working [demo usage](https://github.com/rollbar/rollbar-apple/blob/master/Demos/macosAppObjC/macosAppObjC/AppDelegate.m#L87) app that is part of the SDK workspace.
The transition from rollbar-ios to rollbar-apple does require some code changes on your part. However, if your rollbar-ios integration surface is localized enough it should be a very small effort.
I would more than happy to assist you if you do decide to give it a try. Also, in this case,  I would highly recommend you integrating the rollbar-apple SDK via Swift Package Manager. Integrations via Cocoapods and Carthage are also available, except that the SDK Cocoapod for PLCrashReporter option is not available at the moment.
