### ISSUE TITLE
why rollbar always send report EXC_BREAKPOINT (5): Application terminated

### ISSUE THREAD

**Issue by sdiik** [rollbar/rollbar-ios#345]
<img width="812" alt="Screen Shot 2021-05-20 at 10 49 45" src="https://user-images.githubusercontent.com/17142848/118916416-188c2e00-b959-11eb-8da3-9c173db3f4a7.png">

I am confused which position is wrong ???  please help me
I test in develop is fine but in production always have this bugs .

<img width="871" alt="Screen Shot 2021-05-20 at 10 51 12" src="https://user-images.githubusercontent.com/17142848/118916509-4cffea00-b959-11eb-8bf8-c453cbc25865.png">

**Comment by akornich** [comment]
@sdiik , just as a wild guess, maybe because the application hosting the SDK crashed?...
Is it a crash report occurrence? 
Can you provide here a link to the item in question (on your project's Rollbar Dashboard)?

**Comment by sdiik** [comment]
> @sdiik , just as a wild guess, maybe because the application hosting the SDK crashed?...
> Is it a crash report occurrence?
> Can you provide here a link to the item in question (on your project's Rollbar Dashboard)?

ok mr @akornich  I  asked  for approval from my supervisor first.

mr @akornich  can you provide complete rollbar documentation or reference. such as telemetry , sending correct crash reports with swift language, I read in rollbar doc website use objective-C 
please 🙏🏼

**Comment by akornich** [comment]
The SDK documentation is here: https://docs.rollbar.com/docs/ios
Also, if you are just starting using Rollbar, I would recommend moving to Rollbar-Apple SDK (Rollbar-iOS is at the end of its life-cycle):
https://github.com/rollbar/rollbar-apple
https://docs.rollbar.com/docs/apple

**Comment by sdiik** [comment]
> Can you provide here a link to the item in question (on your project's Rollbar Dashboard)?

mr @akornich this is my rollbar dasboard link : 
https://rollbar.com/HungryHub/iOS/items/16/occurrences/164708858989/

**Comment by sdiik** [comment]
> The SDK documentation is here: https://docs.rollbar.com/docs/ios
> Also, if you are just starting using Rollbar, I would recommend moving to Rollbar-Apple SDK (Rollbar-iOS is at the end of its life-cycle):
> https://github.com/rollbar/rollbar-apple
> https://docs.rollbar.com/docs/apple

thank  mr @akornich

**Comment by akornich** [comment]
@sdiik , thanks for posting the link. It looks like you are using the SDK correctly. The reason the crash report's call stack is not symboicated is that you do not have a dSYM bundle uploaded to the project for the 5.8.22 version (the latest uploaded one is 5.8.21). Once it is uploaded, all the new occurrences coming from that version of your app should be symbolicated.

**Comment by akornich** [comment]
The reason you are getting that specific error reported is that your app crashed and when it restarts again the SDK's crash reporter picks up the crash report created by the terminated app and sends it to rollbar. Once, the crash's call stack gets symbolicated you should be able to pinpoint the actual cause of the crash.

**Comment by sdiik** [comment]
> @sdiik , thanks for posting the link. It looks like you are using the SDK correctly. The reason the crash report's call stack is not symboicated is that you do not have a dSYM bundle uploaded to the project for the 5.8.22 version (the latest uploaded one is 5.8.21). Once it is uploaded, all the new occurrences coming from that version of your app should be symbolicated.

thanks mr @akornich . i will check again

**Comment by akornich** [comment]
@sdiik , can we close the issue? i assume you are unblocked by now...

**Comment by akornich** [comment]
closing due to no replies...
