### ISSUE TITLE
Question: How to include telemetry `extraData` and then viewing it.

### ISSUE THREAD

**Issue by teejayhh** [rollbar/rollbar-ios#347]
Hello I am wondering how we can make use of the `extraData` argument, which is available for many of the telemetry functions.

```swift
rollBar.recordErrorEvent(for: level.rollbarLevel, message: message, extraData: extraData)
```
extraData takes and optional dictionary `[String: Any]?` which we use to augment the event with a few other useful information. Unfortunately I can not see any of this data in the userinterface.

```swift
rollbar.recordErrorEvent(for: .warning, message: "Web View failed to navigate", extraData: ["url": webView.url?.absoluteString ?? "", "error": error.localizedDescription])
```
<img width="1190" alt="Screen Shot 2021-10-01 at 9 10 52 am" src="https://user-images.githubusercontent.com/2525235/135541566-6bcb42bd-a22d-49a0-ac11-90f497b4ea7b.png">

There is no way to see this extra information or I am missing something. 

As a workaround we could dump everything into the `message`, but that would be messy. 

Are we doing something wrong or do we need enable something somewhere ?

Cheers Thomas

**Comment by akornich** [comment]
@teejayhh , did you look at the telemetry events reported within the raw payload JSON of an occurrence? All the relevant telemetry events (including their extra data) should appear there.

**Comment by teejayhh** [comment]
Ah, ok I can see the information on the occurrence.  Thanks for your help.

**Comment by akornich** [comment]
@teejayhh , you are welcome! Please, plan on switching to our alternative SDK for Apple platforms: https://github.com/rollbar/rollbar-apple
All the new feature development is happening there. Rollbar-iOS is already marked for retirement.
