### ISSUE TITLE
Insecure malloc function is used instead of calloc in Rollbar

### ISSUE THREAD

**Issue by Gautam-zodape** [rollbar/rollbar-ios#348]
We are getting error in PEN Test for iOS application which used rollbar.
PEN Test check for the security performance of app. We used mobSF (https://mobsf.github.io/Mobile-Security-Framework-MobSF/) tool for the PEN Test.

We get following error in Security PEN Test-
1. Insecure malloc function is used instead of calloc :- 

malloc is insecure to use and we have calloc as safe alternative of it which should be used.
Do you have any plan for updating this function in your library?
If yes then will it be available in next release or any ETA will be very helpful for me.

**Comment by Gautam-zodape** [comment]
Hi Team,
I am waiting for your reply for the issue.
Could you update on it ASAP?

**Comment by cyrusradfar** [comment]
Hi there! We are looking into this so we can follow up.

**Comment by akornich** [comment]
@Gautam-zodape, may i ask you to provide the location of the malloc call(s) in the SDK codebase?

**Comment by Gautam-zodape** [comment]
Thanks for the reply..

Following are the locations and line number of the malloc function in Rollbar code -
KSKrashMonitor_NSException : Line Number 71
KSKrashMonitor_Signal : Line Number 131, 148
KSKrashMonitor_System : Line Number 130, 142
KSKrashReport : Line Number 1829
KSKrashReport_Fixer : Line Number 332, 335
KSString : Line Number 79
KSFileUtils : Line Number 171, 289
KSJSONCodecObjC : Line Number 130
KSLogger : Line Number 307

**Comment by Gautam-zodape** [comment]
Hi Team 
do you have any update on this ticket?
