### ISSUE TITLE
Python 2.x is removed from MACOS 12.3

### ISSUE THREAD

**Issue by teejayhh** [rollbar/rollbar-ios#349]
Back in macOS Catalina they have announced the depreciation of python 2.
Now with 12.3 it happened and breaks the  `upload .dsym script` as it uses `/usr/bin/python`

https://macmule.com/2022/01/29/macos-monterey-12-3-will-remove-python-2-7-usr-bin-python/

**Comment by rollbar-bborsits** [comment]
We released the [Rollbar Apple SDK](https://github.com/rollbar/rollbar-apple) v3.0.0, which deprecates the Rollbar iOS SDK. The Apple SDK is a modernized approach to collecting errors from Apple devices and fixes many iOS SDK problems and pain points. Please, consider migrating over to the Apple SDK. You can find its documentation [here](https://docs.rollbar.com/docs/apple). Feel free to open an [issue](https://github.com/rollbar/rollbar-apple/issues) or contact our support if you encounter any difficulties.
