### ISSUE TITLE
getting error for Rollbar with xCode 13.3.1

### ISSUE THREAD

**Issue by Gautam-zodape** [rollbar/rollbar-ios#350]
I am using Rollbar library from 4-5 years and it was working fine with xCode 13. But i upgrade xcode to 13.3.1 and i am getting following error-
Command PhaseScriptExecution failed with a nonzero exit code

Error could be due to python script in Run Script so i update my script from "https://raw.githubusercontent.com/rollbar/rollbar-ios/master/upload_dsym.py" but error still there.
Following is the path and error log details:- 
/bin/sh: /Users/gautamzodape/Library/Developer/Xcode/DerivedData/coinout-ios-eepqxldbqcazutefgimznrnxrlpr/Build/Intermediates.noindex/coinout-ios.build/Debug-iphoneos/coinout-uat.build/Script-721F61C5278C63DA007947C6.sh: /usr/bin/python: bad interpreter: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

**Comment by waltjones** [comment]
This package is working for me with no issues on Xcode 14.2.

This error, `/usr/bin/python: bad interpreter: No such file or directory`, looks like python isn't installed or is at an unexpected location.

**Comment by rollbar-bborsits** [comment]
We released the [Rollbar Apple SDK](https://github.com/rollbar/rollbar-apple) v3.0.0, which deprecates the Rollbar iOS SDK. The Apple SDK is a modernized approach to collecting errors from Apple devices and fixes many iOS SDK problems and pain points. Please, consider migrating over to the Apple SDK. You can find its documentation [here](https://docs.rollbar.com/docs/apple). Please open an [issue](https://github.com/rollbar/rollbar-apple/issues) or contact our support if you have any problems.
