### ISSUE TITLE
Getting warning in penetration testing due to KSKRash of Rollbar

### ISSUE THREAD

**Issue by Gautam-zodape** [rollbar/rollbar-ios#351]
We are getting error in PEN Test for iOS application which used rollbar.
PEN Test check for the security performance of app. We used mobSF (https://mobsf.github.io/Mobile-Security-Framework-MobSF/) tool for the PEN Test.

We get following error in Security PEN Test-

Insecure malloc function is used instead of calloc :-
malloc is insecure to use and we have calloc as safe alternative of it which should be used.

**Comment by rollbar-bborsits** [comment]
We released the [Rollbar Apple SDK](https://github.com/rollbar/rollbar-apple) v3.0.0, which deprecates the Rollbar iOS SDK. The Apple SDK is a modernized approach to collecting errors from Apple devices and fixes many iOS SDK problems and pain points. Please, consider migrating over to the Apple SDK. You can find its documentation [here](https://docs.rollbar.com/docs/apple). Please open an [issue](https://github.com/rollbar/rollbar-apple/issues) or contact our support if you encounter problems.
