### ISSUE TITLE
PhaseScriptExecution Run Script issue

### ISSUE THREAD

**Issue by NaleSupriya** [rollbar/rollbar-ios#352]
In my current project , I'm using Rollbar scrip for crash report generation,
Here is the script
[run script.txt](https://github.com/rollbar/rollbar-ios/files/8590967/run.script.txt)

But while creating build only I'm getting error :

/bin/sh: /Users/pslmacuser/Library/Developer/Xcode/DerivedData/<APPNAME>-fnvxopdztdzglqbuqamcejjadxiu/Build/Intermediates.noindex/ArchiveIntermediates/coinout-qa/IntermediateBuildFilesPath/coinout-ios.build/Release-iphoneos/<APPNAME>.build/Script-D090B8B628081FAC00983739.sh: /usr/bin/python: bad interpreter: No such file or directory
Command PhaseScriptExecution failed with a nonzero exit code

I have tried to check this run script with multiple Xcode versions like Xcode 13.1, 13.2.1, 13.3 but its showing same error for all.
But previously it was working on Xcode 13.1 and 13.3, recently I have just updated MacOS to 12.3.1

So will this script is impacting due to macOS version changes?
And any work around to fix this issue?

Current Mac OS: 12.3.1
Xcode : 13.1, 13.2.1, 13.3
Swift version : Swift4

**Comment by siki88** [comment]
targets -> {project} -> Build Phases -> Upload Rollbar debug symbol -> "change shell address to:" /usr/bin/python3

**Comment by rollbar-bborsits** [comment]
We released the [Rollbar Apple SDK](https://github.com/rollbar/rollbar-apple) v3.0.0, which deprecates the Rollbar iOS SDK. The Apple SDK is a modernized approach to collecting errors from Apple devices and fixes many iOS SDK problems and pain points. Please, consider migrating over to the Apple SDK. You can find its documentation [here](https://docs.rollbar.com/docs/apple). Please open an [issue](https://github.com/rollbar/rollbar-apple/issues) or contact our support if you encounter problems.
