### ISSUE TITLE
Any plans to move to either XCFramwork or SPM?

### ISSUE THREAD

**Issue by piercifani** [rollbar/rollbar-ios#355]
Otherwise this project is not possible to integrate in any modern Xcode project setup.

**Comment by nekto-zum** [comment]
@piercifani you can switch to https://github.com/rollbar/rollbar-apple.

**Comment by rollbar-bborsits** [comment]
We released the [Rollbar Apple SDK](https://github.com/rollbar/rollbar-apple) v3.0.0, which deprecates the Rollbar iOS SDK. The Apple SDK is a modernized approach to collecting errors from Apple devices and fixes many iOS SDK problems and pain points. Please, consider migrating over to the Apple SDK. You can find its documentation [here](https://docs.rollbar.com/docs/apple). Please open an [issue](https://github.com/rollbar/rollbar-apple/issues) or contact our support if you encounter problems.
