### ISSUE TITLE
Carthage support?

### ISSUE THREAD

**Issue by btc** [rollbar/rollbar-ios#37]
Is there any plan to add Carthage support?

**Comment by stclairdaniel** [comment]
It's not currently on our roadmap, but I'm happy to make sure your feedback is noted. I'll keep you in the loop if there are any developments.

**Comment by ezarowny** [comment]
Yup! It's a little complicated but I'm working on it. There's a refactor in progress on that allows for a much more modern dynamic framework build. I've made good progress and you can follow the branch if you'd like; it's `target-refactor`.

Additionally, our current crash reporter has to be compiled ahead of time so we can't add it as a Carthage dependency. This is more of a nice to have but we're currently evaluating another crash reporter.

**Comment by btc** [comment]
Thanks for the quick response.

**Comment by rokob** [comment]
This should be easy with the new v1 if we change crash reporting frameworks, adding to that milestone.

**Comment by demonar** [comment]
+1

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!

**Comment by kelvinlauKL** [comment]
Looking for Carthage support 👍

**Comment by rokob** [comment]
We support Carthage. Integrating Rollbar should be as easy as adding this to your Cartfile:

```
github "rollbar/rollbar-ios" ~> 1.5
```

and following the [additional steps](https://github.com/Carthage/Carthage#getting-started) required for adding all dependencies with Carthage. I just added this to our [docs](https://docs.rollbar.com/v1.0.0/docs/ios#section-with-carthage-https-github-com-carthage-carthage-).
