### ISSUE TITLE
Warning: 'atomic' attribute does not match the inherited property

### ISSUE THREAD

**Issue by zhenyakoval** [rollbar/rollbar-ios#38]
Hi!
I've integrated version 0.2.0 via CocoaPods (XCode 8.2.1) and there are several warnings:
![standalone xcworkspace 2017-02-02 15-43-46](https://cloud.githubusercontent.com/assets/2639123/22551903/730fcf72-e95f-11e6-966f-798c79a678ee.png)

```personId```, ```personUsername```, ```personEmail``` have different attributes in ```RollbarConfiguration.h``` and ```RollbarConfiguration.m files```.

What is the reason of such difference?

**Comment by pouriaalmassi** [comment]
Also seeing this warnings. Any updates on this? Cheers. 

```
/path/to/my/project/Pods/Rollbar/Rollbar/RollbarConfiguration.m:21:39: 'atomic' attribute on property 'personId' does not match the property inherited from 'RollbarConfiguration'

/path/to/my/project/Pods/Rollbar/Rollbar/RollbarConfiguration.m:22:39: 'atomic' attribute on property 'personUsername' does not match the property inherited from 'RollbarConfiguration'

/path/to/my/project/Pods/Rollbar/Rollbar/RollbarConfiguration.m:23:39: 'atomic' attribute on property 'personEmail' does not match the property inherited from 'RollbarConfiguration'
```

**Comment by vGubriienko** [comment]
Issue still exists on XCode 8.3

**Comment by rokob** [comment]
This will be fixed as part of the new v1 release, I am going to defer until that, sorry for the delay on this one.
