### ISSUE TITLE
Use of undeclared type 'RollbarConfiguration'

### ISSUE THREAD

**Issue by viraj** [rollbar/rollbar-ios#42]
I get a Swift compiler Error "Use of undeclared type 'RollbarConfiguration'" in the following 

`let config: RollbarConfiguration = RollbarConfiguration() ` line.
I use Swift, iOS 10.2+ with Xcode 8.2.1

What might be the issues ? Any feedback is appreciated. 

Update: Work perfectly without Cocoapods.

**Comment by rokob** [comment]
My first thought is just to double check that you have a bridging header file that is being properly included and that it contains

```objc
#import <SystemConfiguration/SystemConfiguration.h>
#import <Rollbar/Rollbar.h>
```

**Comment by viraj** [comment]
@rokob yes that is included.

**Comment by otusweb** [comment]
SAme issue, though it does not work by dropping the framework in the project manually either
Xcode 8.3.2 swift project

**Comment by otusweb** [comment]
Resolved the issue by adding 
`import Rollbar`
