### ISSUE TITLE
How about support for macOS?

### ISSUE THREAD

**Issue by martnst** [rollbar/rollbar-ios#45]
Hi have an app with both an iOS and a macOS version and would like to track errors from both of them into rollbar. Do you have any plans on also supporting macOS?

**Comment by martnst** [comment]
Update: 

I managed to get it running and post items on macOS, by making some adjustments to it locally. There are some downside still though: 
- I had to drop support for the CrashReporter, as it uses a precompiled iOS Framework. 
- It requires me to use the server post token instead of the client's one as `macOS` is an unknown platform.

**Comment by rokob** [comment]
Moving to KSCrash should resolve this issue and is something we are planning as part of the v1 release. Adding to that milestone so we can track support for macOS.

**Comment by rokob** [comment]
Note, we need to make a backend change to allow macOS as the platform and support a client side token.

**Comment by rokob** [comment]
Since we have moved to KSCrash, this should just work. I can add `macOS` to the allowable client-side platforms to address the other issue.

**Comment by jtoy** [comment]
is there going to be official support? We have multiple apps including Mac and this is preventing us from using rollbar

**Comment by akornich** [comment]
#168

**Comment by akornich** [comment]
@jtoy, @martnst  (or anyone else interested in using Rollbar-iOS on macOS), would you be able to give a test run to our latest v1.8.0-alpha8 release on both iOS and macOS? The corresponding CocoaPod is also available. Preferably during this week. 
Thank you!

**Comment by akornich** [comment]
done.
