### ISSUE TITLE
Custom Fingerprint

### ISSUE THREAD

**Issue by lukas-gitl** [rollbar/rollbar-ios#59]
Is this possible or even necessary? 
https://rollbar.com/docs/grouping-algorithm/#customizing-fingerprints-in-code

Cheers, L~

**Comment by rivkahstandig3636** [comment]
Hi there, It is not currently possible, but will be in a few weeks. We'll reply here once the SDK has been updated. Thanks for asking!

**Comment by akornich** [comment]
it seems to me that the most logical way, in my opinion, for custom fingerprint calculation would be to have it as (or as part of) the custom defined payloadModification callback. But that would mean we do not have to do anything for this work item, except maybe updating the docs with this recommendation.

**Comment by rivkahstandig3636** [comment]
Hm, @rokob do you agree?

**Comment by rokob** [comment]
Yeah that seems reasonable. 1) It is not necessary to set a custom fingerprint, it should be handled correctly by the backend and there are tools in the UI for doing custom grouping. 2) If you wish to set a custom fingerprint, the `payloadModificationBlock` can be used to make it happen.
