### ISSUE TITLE
Very small issue with missing license in Cocoapods

### ISSUE THREAD

**Issue by JustinDSN** [rollbar/rollbar-ios#6]
When I add ```'pod 'Rollbar', '~> 0.1.2'``` to my ```Podfile``` and run ```pod install```.  It produces the below warning, this is likely that a license file wasn't present in the repository when the 0.1.2 tag was created.

[!] Unable to read the license file `/Users/Justin/Projects/Cookbrite/ios/Pods/Rollbar/LICENSE` for the spec `Rollbar (0.1.2)`

**Comment by ezarowny** [comment]
I don't know when this was fixed but it was. Cheers!
