### ISSUE TITLE
Update podspec for KSCrash

### ISSUE THREAD

**Issue by rokob** [rollbar/rollbar-ios#65]
The current podspec is designed to work with the PLCrashReporter framework. After moving to use KSCrash as the crash reporter dependency, the podspec no longer resolves all of the transitive dependencies correctly.

**Comment by rivkahstandig3636** [comment]
Hi there, I’m closing out all issues opened before 2018 that haven’t had any activity on them since the start of this year. If this is still an issue for you, please comment here and we can reopen this. Thanks!
