### ISSUE TITLE
Getting Unable to satisfy the following requirements while installing Rollbar

### ISSUE THREAD

**Issue by RollbarExample** [rollbar/rollbar-ios#68]
Hi,

I am trying to install Rollbar notifier inside my sample application by followed steps.

1. Added the below content inside pod file.

platform :ios, '7.0'

target 'Rollbar-Example' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!
pod "Rollbar", "~> 1.0.0-alpha"
end

2. Ran the pod install but getting the following error.

![snip20180119_2](https://user-images.githubusercontent.com/32199575/35149624-dc49d068-fd3c-11e7-89e6-77c41356b7df.png)

I have created the sample application repository, Here is the link fi want more info.
https://github.com/RollbarExample/Rollbar-Ios-Example

Please help me out.

**Comment by rokob** [comment]
Rollbar 1.0+ doesn't work properly with Cocoapods which is clearly stated in the README. This is a problem with Cocoapods not working correctly with C++ libraries.
