### ISSUE TITLE
Crash report is not symbolized and crashLevel does not work

### ISSUE THREAD

**Issue by VicZhang1** [rollbar/rollbar-ios#76]
Hi,

I have configured Rollbar in my project as below by using v1.0.0-alpha6, it did send crash report to Rollbar website, I can see it, but the crash report is not symbolized, I contacted Rollbar support, they replied me that the crash report is stored in `message` field, it's wrong, it should be stored in `crash_report` field.

```
RollbarConfiguration *config = [RollbarConfiguration configuration];
config.crashLevel = @"critical";
config.environment = isDevMode ? @"Development" : @"Production";
[config setRequestId: [NSString stringWithFormat:@"Request-%f", [[NSDate date] timeIntervalSince1970]]];
[config setCaptureLogAsTelemetryData:NO];
[config setCaptureConnectivityAsTelemetryData:YES];
[config setPersonId:userHash username:userHash email:nil];
[config setNotifierName:userHash version:version];
    
[Rollbar initWithAccessToken:@"<my project access token>" configuration:config];
```

By the way, as above, I configured the `crashLevel` to **critical**, but on Rollbar website, I see crash item is still **Error** level.

Any comments?

Thanks,
-
Vic

**Comment by VicZhang1** [comment]
I cloned this repo, and see that the `crashLevel` property in configuration is only used in `-logCrashReport:` method of `RollbarNotifier`, but the `-logCrashReport:` is **never** called.

**Comment by VicZhang1** [comment]
Note, I followed your guild to upload dSYM to Rollbar by using https://raw.githubusercontent.com/rollbar/rollbar-ios/master/upload_dsym.py, I can see dSYM files on "dSYMs" section on Rollbar project settings page.

**Comment by ajtran** [comment]
internal: https://app.intercom.io/a/apps/rlisg82q/inbox/inbox/849049/conversations/14946744364

**Comment by VicZhang1** [comment]
@ajtran, what's the link? I don't have an intercom account.

**Comment by VicZhang1** [comment]
@ajtran  @rokob Any updates?

**Comment by rokob** [comment]
You are certainly right that `logCrashReport` was never called. This was all an oversight in the switch over to KSCrash, I have a PR up that should fix things and I will release a new version with the fix soon.

**Comment by VicZhang1** [comment]
Thanks @rokob , but I am unable to unzip [v1.0.0-alpha7](https://github.com/rollbar/rollbar-ios/releases/tag/v1.0.0-alpha7) , I get:
![image](https://user-images.githubusercontent.com/2956318/38461556-5e505292-3b06-11e8-991f-af140637e5b4.png) 

I also tried to unzip this on Windows, I also get an error. I guess the zip file is broken.

**Comment by rokob** [comment]
Ah it got corrupted on upload, I just reuploaded it same link https://github.com/rollbar/rollbar-ios/releases/download/v1.0.0-alpha7/Rollbar.zip my download appeared to work, let me know if there is a further issue.

**Comment by VicZhang1** [comment]
Thanks @rokob , the https://github.com/rollbar/rollbar-ios/releases/download/v1.0.0-alpha7/Rollbar.zip  works for me now. I will check if this has been fixed and close this.

**Comment by VicZhang1** [comment]
It works for me now, thanks a lot. I will close this. Last questions(won't block this to close): how long will the uploaded dSYM files be kept on Rollbar website? or how many dSYM files will be kept?
