### ISSUE TITLE
Fatal Exception: NSInvalidArgumentException (data parameter is nil)

### ISSUE THREAD

**Issue by claygraffix** [rollbar/rollbar-ios#78]
Hi, we are seeing this crash reported inside of Crashlytics.  We are using Rollbar to record app errors, and Crashlytics for crashes.  It's pretty rare, but it happens enough that we need to look into it.  We are using the latest framework released here.

Here's the log data:
`Fatal Exception: NSInvalidArgumentException
0  (Missing)                      0x18118ad8c (Missing)
1  (Missing)                      0x1803445ec (Missing)
2  (Missing)                      0x18118ac6c (Missing)
3  (Missing)                      0x181af8360 (Missing)
4  Freebird                       0x103340ffc -[RollbarNotifier initWithAccessToken:configuration:isRoot:] (RollbarNotifier.m:57)
5  Freebird                       0x1033530b4 +[Rollbar initWithAccessToken:configuration:enableCrashReporter:] (Rollbar.m:43)
6  Freebird                       0x102f9f750 AppDelegate.application(_:didFinishLaunchingWithOptions:) (AppDelegate.swift:80)
7  Freebird                       0x102fa28a0 @objc AppDelegate.application(_:didFinishLaunchingWithOptions:) (AppDelegate.swift)
8  UIKit                          0x18ad5ae38 -[UIApplication _handleDelegateCallbacksWithOptions:isSuspended:restoreState:]
9  UIKit                          0x18ad5a240 -[UIApplication _callInitializationDelegatesForMainScene:transitionContext:]
10 UIKit                          0x18ad2765c -[UIApplication _runWithMainScene:transitionContext:completion:]
11 UIKit                          0x18b357a0c __111-[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]_block_invoke
12 UIKit                          0x18ad26e4c +[_UICanvas _enqueuePostSettingUpdateTransactionBlock:]
13 UIKit                          0x18ad26ce8 -[__UICanvasLifecycleMonitor_Compatability _scheduleFirstCommitForScene:transition:firstActivation:completion:]
14 UIKit                          0x18ad25b78 -[__UICanvasLifecycleMonitor_Compatability activateEventsOnly:withContext:completion:]
15 UIKit                          0x18b9bb72c __82-[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]_block_invoke
16 UIKit                          0x18ad25268 -[_UIApplicationCanvas _transitionLifecycleStateWithTransitionContext:completion:]
17 UIKit                          0x18b7a09b8 __125-[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]_block_invoke
18 UIKit                          0x18b8eeae8 _performActionsWithDelayForTransitionContext
19 UIKit                          0x18ad24c88 -[_UICanvasLifecycleSettingsDiffAction performActionsForCanvas:withUpdatedScene:settingsDiff:fromSettings:transitionContext:]
20 UIKit                          0x18ad24624 -[_UICanvas scene:didUpdateWithDiff:transitionContext:completion:]
21 UIKit                          0x18ad2165c -[UIApplication workspace:didCreateScene:withTransitionContext:completion:]
22 UIKit                          0x18ad213ac -[UIApplicationSceneClientAgent scene:didInitializeWithEvent:completion:]
23 (Missing)                      0x183988470 (Missing)
24 (Missing)                      0x183990d6c (Missing)
25 (Missing)                      0x180a7cae4 (Missing)
26 (Missing)                      0x180ab8b0c (Missing)
27 (Missing)                      0x1839bc878 (Missing)
28 (Missing)                      0x1839bc51c (Missing)
29 (Missing)                      0x1839bcab8 (Missing)
30 (Missing)                      0x181133404 (Missing)
31 (Missing)                      0x181132c2c (Missing)
32 (Missing)                      0x18113079c (Missing)
33 (Missing)                      0x181050da8 (Missing)
34 (Missing)                      0x183033020 (Missing)
35 UIKit                          0x18b03178c UIApplicationMain
36 Freebird                       0x102faa744 main (AppDelegate.swift:21)
37 (Missing)                      0x180ae1fc0 (Missing)`

Image also from Crashlytics, since the log isn't easily readable...
![image](https://user-images.githubusercontent.com/1283083/39203274-26e8f4bc-47a9-11e8-9996-6f2977a391da.png)

Any ideas?  Thanks!

**Comment by rokob** [comment]
Looking, that stack trace makes me think we might have a stray JSON (de)serialization without a guard on the input being non-nil.
