### ISSUE TITLE
Add capture uncaught config option

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/rollbar-ios#85]
Similar to rollbar.js, the ability to turn on/off uncaught error reporting.

**Comment by akornich** [comment]
@rivkahstandig3636, does it mean that in context of Rollbar-iOS this option means enable/disable reporting crash reports within RollbarKSCrashReportSink?

**Comment by rivkahstandig3636** [comment]
It means that we need a way to completely disable or enable sending items to Rollbar from this SDK.

**Comment by akornich** [comment]
@rivkahstandig3636 , but isn't it the "enable" flag that we already have implemented?
for example, in the .NET SDK we have "enable" flag essentially turns Rollbar notifier on or off and we have CaptureUncaughtExceptions flag that is only applicable when Rollbar.NET is used within ASP.NET web request processing pipeline (for other types of hosting apps it does not make sense unless it is part of plug in supported by the application specific framework).

**Comment by rivkahstandig3636** [comment]
Yes, sorry, for some reason I thought that's what I was commenting on (the enable/disable flag). I see now I'm commenting on an entirely different issue. Ignore my previous comment.

**Comment by rivkahstandig3636** [comment]
As for your original question, I'll PM you about this.

**Comment by akornich** [comment]
this repo is retiring. all the new feature development will be happening under the new [Rollbar-Apple SDK](https://github.com/rollbar/rollbar-apple) that is replacing this SDK. closing...
