### ISSUE TITLE
Add max items config option

### ISSUE THREAD

**Issue by rivkahstandig3636** [rollbar/rollbar-ios#86]
Similar to rollbar.js maxItems

**Comment by akornich** [comment]
@rivkahstandig3636 , can you, please, clarify on this one? we just added max items rate config option in v1.1.0. what exactly max limit this one is about?

**Comment by akornich** [comment]
this repo is retiring. all the new feature development will be happening under the new [Rollbar-Apple SDK](https://github.com/rollbar/rollbar-apple) that is replacing this SDK. closing...
