### ISSUE TITLE
pod not available via cocoapods

### ISSUE THREAD

**Issue by donhill** [rollbar/rollbar-ios#97]
I have run pod repo update and still get this issue.

Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Rollbar (~> 1.0.0-alpha)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Rollbar (~> 1.0.0-alpha)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.

**Comment by tejinderpaul** [comment]
installation is not working tho.


*Regards,*TEJINDER PAUL SINGH,
————————————————————
Skype: tpsingh1430
Mobile: +919501414920
EmailID: tps.teji@gmail.com

**Comment by rokob** [comment]
1.0.0-alpha11 is available on Cocoapods

**Comment by tejinderpaul** [comment]
Hi, 
Please check error I am facing when installed Rollbar vis cocoapods:
  pod 'Rollbar', '~> 1.0.0-alpha11'
My project is in Objective C
.
![screenshot 2018-06-01 12 06 48](https://user-images.githubusercontent.com/8290274/40825114-4a70b844-6594-11e8-9abd-33246e9cdd0d.png)
