### ISSUE TITLE
 Showing Recent Issues clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by tejinderpaul** [rollbar/rollbar-ios#99]
When I import Rollbar framework in my project, Xcode do not compile and throws the error: 
Showing Recent Issues
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I followed the steps given in rollbar and added libc++ library. 
Please check screenshots for more information.
![screenshot 2018-05-17 10 23 45](https://user-images.githubusercontent.com/8290274/40157412-790c4bfc-59bc-11e8-9969-88579dffe0be.png)
![screenshot 2018-05-17 10 24 49](https://user-images.githubusercontent.com/8290274/40157422-8de196c2-59bc-11e8-8340-b620509cf550.png)
![screenshot 2018-05-17 10 25 26](https://user-images.githubusercontent.com/8290274/40157438-acfda104-59bc-11e8-9525-1e260f668a0b.png)
![screenshot 2018-05-17 10 25 41](https://user-images.githubusercontent.com/8290274/40157439-ad3c91c0-59bc-11e8-8b50-e23811c55516.png)

**Comment by rokob** [comment]
It looks like you are using Swift, do you have a Bridging Header?

**Comment by tejinderpaul** [comment]
I am using Objective C.


*Regards,*TEJINDER PAUL SINGH,
————————————————————
Skype: tpsingh1430
Mobile: +919501414920
EmailID: tps.teji@gmail.com

**Comment by rokob** [comment]
This is due to an Xcode version issue depending on your version versus what the framework was built with. The latest release (https://github.com/rollbar/rollbar-ios/releases/tag/v1.0.0-alpha11) has zip files for 8.3, 9.2, and 9.3.1. Selecting the right framework for your version of Xcode should resolve any linker issues.
